/*CRIE SINÔNIMOS PARA QUE O USUÁRIO USER_APP ACESSE, DE FORMA MAIS SIMPLES, 
AS PROCEDURES INCLUINDO_PRODUTO E INCLUINDO_DADOS_VENDA, BEM COMO AS TABELAS 
PRODUTO_EXERCICIO E PRODUTO_VENDA_EXERCICIO.
USE O MESMO NOME DO OBJETO COMO NOME DO SINÔNIMO
*/

CREATE PUBLIC SYNONYM INCLUINDO_PRODUTO FOR USER_DEV.INCLUINDO_PRODUTO; 
CREATE PUBLIC SYNONYM INCLUINDO_DADOS_VENDA FOR USER_DEV.INCLUINDO_DADOS_VENDA;
CREATE PUBLIC SYNONYM PRODUTO_EXERCICIO FOR USER_DEV.PRODUTO_EXERCICIO;
CREATE PUBLIC SYNONYM PRODUTO_VENDA_EXERCICIO FOR USER_DEV.PRODUTO_VENDA_EXERCICIO;