
--TABELA DE VISUALIZACAO GERAL E POR ORDEM
SELECT * FROM DEPTREE_TEMPTAB;

--EXECUTANDO A PROCEDURE PARA INDICAR OS CAMPOS TIPO DO OBJETO, NOME DO USUARIO DA TABELA, PARAMETRO
EXECUTE DEPTREE_FILL('TABLE', 'USER_DEV', 'PRODUTO_EXERCICIO'); 

--SELECIONANDO A VIEW PARA UMA VISUALIZACAO MELHOR DE DEPENDENCIAS
SELECT NESTED_LEVEL, TYPE, SCHEMA, NAME, SEQ# FROM DEPTREE ORDER BY SEQ#;