--GRANT DÁ PRIVILEGIOS DE UTILIZACAO A PROCEDURE ATUALIZAR_CLI_SEG_MERCADO PARA USER_APP
GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO USER_APP;

--GRANT DÁ PRIVILEGIOS DE UTILIZACAO A PROCEDURE ATUALIZAR_CLI_SEG_MERCADO PARA USER_APP
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO USER_APP;

--GRANT DÁ PRIVILEGIOS DE UTILIZACAO A PROCEDURE ATUALIZAR_CLI_SEG_MERCADO PARA USER_APP
GRANT EXECUTE ON EXCLUIR_CLIENTE TO USER_APP;

--GRANT DÁ PRIVILEGIOS DE UTILIZACAO A PROCEDURE ATUALIZAR_CLI_SEG_MERCADO PARA USER_APP
GRANT EXECUTE ON INCLUIR_CLIENTE TO USER_APP;

--DANDO ACESSO A VISUALIZACAO PARA O USER_APP, APOS TESTES 
GRANT SELECT ON CLIENTE TO USER_APP;

SELECT * FROM CLIENTE;

--ESTAMOS ADICIONANDO DIRETO POR UM INSERT, UTILIZANSO O USER_DEV, O USER MASTER DESTE MODULO
INSERT INTO CLIENTE 
(ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
VALUES
(5, 'PADARIA XYZW', '22/222', 1, TO_DATE('15/01/2022', 'DD/MM/YYYY'), 80000, 'MEDIO GRANDE'); 

ROLLBACK;