/*
CRIANDO PROCEDURE PELO USER_APP, MOSTRANDO QUE OS SINONIMOS PODEM SER UTILZADOS OS SINONIMOS DE USER_DEV
TANTO PARA TABELAS, QUANTO PARA PROCEDURES;
*/

--AS REFERENCIAS SAO OS SINONIMOS DA TABELA CLIENTE DE USER_DEV.
CREATE OR REPLACE PROCEDURE APP_INCLUIR_CLIENTE
    (
    P_ID IN CLIENTE.ID%TYPE,
    P_RAZAO IN CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ IN CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO IN CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
    )
IS
BEGIN
    INCLUIR_CLIENTE(P_ID, P_RAZAO, P_CNPJ,P_SEGMERCADO,  P_FATURAMENTO);
END;

--EXECUTANDO A PROCEDURE CRIADA, UTILIZANDO A CHAMADA DE OUTRA PROCEDURE-----
EXECUTE APP_INCLUIR_CLIENTE(6, 'SEGUNDO CLIENTE INCLUIDO POR USER_APP', '23456', 2, 100000);

--VERIFICANDO INCLUSÃO--------------------------------------------------
SELECT * FROM CLIENTE;