--NAO TEM COMO ADICIONAR DIRETO PELO USER_APP, PORQUE OS ACESSOS SAO APENAS PELAS PROCEDURES
INSERT INTO CLIENTE 
(ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
VALUES
(5, 'PADARIA XYZW', '22/222', 1, TO_DATE('15/01/2022', 'DD/MM/YYYY'), 80000, 'MEDIO GRANDE');


--NEM INDICANDO O USUARIO DONO DA TABELA (MASTER) NAO É POSSIVEL, POIS O ACESSO DADO É APENAS PARA AS PROCEDURES INDICADAS NO GRANT
INSERT INTO USER_DEV.CLIENTE 
(ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
VALUES
(5, 'PADARIA XYZW', '22/222', 1, TO_DATE('15/01/2022', 'DD/MM/YYYY'), 80000, 'MEDIO GRANDE');


--É NECESSÁRIO UTILIZAR A PROCEDURE, SE ACESSAR O USER DEV É POSSIVEL VER A INCLUSAO DO CLIENTE
EXECUTE USER_DEV.INCLUIR_CLIENTE(5, 'PADARIA XYZW', '22222', 1, 80000);

--NO USER_APP NAO É POSSIVEL NESTE MOMENTO;
SELECT * FROM USER_DEV.CLIENTE;
--APOS DAR PERMISSAO O USER_APP CONSEGUE VISUALIZAR A TABELA;