/*
INCLUIMOS AS PROCEDURES E FUNCTIONS DA PROCEDURE INCLUIR_CLIENTE
INCLUIMOS
FORMAT_CNPJ
OBTER_CATEGORIA_CLIENTE
VERIFICA_SEGMENTO_MERCADO

INCLUIDOS APENAS NO BODY DE CLIENTE_PAC
*/

--TESTE COM USER_APP UTILIZANDO DENTRO DO PACOTE
set serveroutput on;
execute cliente_pac.incluir_cliente(18, 'INCLUIR CLIENTE PELO PACOTE USANDO PROC INTERNA', '222222', 2, 50000);

--TESTE COM USER_APP UTILIZANDO FORA DO PACOTE
set serveroutput on;
execute incluir_cliente(19, 'INCLUIR CLIENTE FORA DO PACOTE USANDO PROC INTERNA', '222222', 2, 50000);

select * from cliente;