--ESTA TABELA ESTARÁ VAZIA, SO TERÁ RESULTADOS APÓS A DEPTREE_FILL
--SER ADICIONADO O DADOS DE DEPENDENCIA
--ESTE MODELO NAO MOSTRA MUITO AMIGAVEL AS DEPENDENCIAS
SELECT * FROM DEPTREE_TEMPTAB;

--TIPO DO OBJETO, NOME DO USUARIO DA TABELA, PARAMETRO
EXECUTE DEPTREE_FILL('TABLE', 'USER_DEV', 'CLIENTE'); 

--VIZUALIZAR PELA VIEW DEPTREE
SELECT NESTED_LEVEL, SCHEMA, TYPE, NAME, SEQ# FROM DEPTREE ORDER BY SEQ#;