CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
(P_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN
    CLIENTE.CATEGORIA%TYPE --MESMO TIPO DO CAMPO
IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF P_FATURAMENTO <= 10000 THEN
        V_CATEGORIA := 'PEQUENO';
    ELSIF P_FATURAMENTO <= 50000 THEN
        V_CATEGORIA := 'MEDIO';
    ELSIF P_FATURAMENTO <= 100000 THEN
        V_CATEGORIA := 'MEDIO GRANDE';
    ELSE
        V_CATEGORIA := 'GRANDE';
    END IF;
    RETURN V_CATEGORIA;
END;



--TESTAR FUNCAO----------
VARIABLE G_CATEGORIA VARCHAR2(100);
EXECUTE :G_CATEGORIA:= CATEGORIA_CLIENTE(190000);
PRINT G_CATEGORIA;