CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
    (
    P_ID CLIENTE.ID%TYPE, 
    P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE,
    P_CATEGORIA CLIENTE.CATEGORIA%TYPE
    )
IS
BEGIN
    INSERT INTO CLIENTE
    VALUES
    (
    P_ID,
    P_RAZAO,
    P_CNPJ,
    P_SEGMERCADO,
    SYSDATE,
    P_FATURAMENTO,
    P_CATEGORIA
    );
    COMMIT;
END;


SELECT * FROM CLIENTE;

--INSEERINDO CLIENTES-----------------------------------------------------
BEGIN
    INCLUIR_CLIENTE(1, 'SUPERMERCADOS CAMPEAO', '1234567890', 1, 90000, 'MEDIO GRANDE');
END;