--NESTE CASO A PROCEDURE, A CTEGORIA É SELECIONADA DE OUTRA PROCEDURE,
--POR ESTE MOTIVO CATEGORIA VIROU UMA VARIÁVEL;

CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
    (
    P_ID CLIENTE.ID%TYPE, 
    P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE

    )
IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);

    INSERT INTO CLIENTE
    VALUES
    (
    P_ID,
    P_RAZAO,
    P_CNPJ,
    P_SEGMERCADO,
    SYSDATE,
    P_FATURAMENTO,
    V_CATEGORIA
    );
    COMMIT;
END;

SELECT * FROM CLIENTE;

EXECUTE INCLUIR_CLIENTE(2,'SUPERMERCADO DO VALE', '11111111111', 1, 900000);
EXECUTE INCLUIR_CLIENTE(3,'SUPERMERCADO CARIOCA', '22222222222', 1, 30000);