--PROCEDURE PARA INCLUIR
CREATE PROCEDURE INCLUIR_SEGMERCADO
--NOME DA PROCEDURE E PARAMETROS DE INICIO DA PROCEDURE
(P_ID IN NUMBER, P_DESCRICAO IN VARCHAR2)
IS 
--SEMELHANTE AO DECLARE
BEGIN
--CONTEUDO DA PROCEDURE
    INSERT INTO SEGMERCADO (ID,DESCRICAO) VALUES(P_ID, UPPER(P_DESCRICAO));
    COMMIT;
END;

SELECT * FROM SEGMERCADO; 


---------------------------------EXECUCAO----------------------------------
--FORMAS DE EXECUTAR A PROCEDURE
EXECUTE INCLUIR_SEGMERCADO(4,'Farmaceuticos');

--OUTRA FORMA
BEGIN
    INCLUIR_SEGMERCADO(4,'Farmaceuticos');
END;

