--ALTERAR O VAREJO PARA VAREJISTA, ATACADO, ATACADISTA, INDUSTRIA PARA INDUSTRIAL
DECLARE
    V_ID SEGMERCADO.ID%TYPE := 3;
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacadista';
BEGIN
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    V_ID := 1;
    v_DESCRICAO := 'Varejista';
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    V_ID := 2;
    v_DESCRICAO := 'Industrial';
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    COMMIT;
END;

SELECT * FROM SEGMERCADO;