--INCLUSAO---------------------------------------
DECLARE
    V_ID SEGMERCADO.ID%TYPE := 5;
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Esportista';
BEGIN
    INSERT INTO SEGMERCADO (ID,DESCRICAO) VALUES(V_ID, UPPER(V_DESCRICAO));
    COMMIT;
END;

-----ALTERACAO--------------------
DECLARE
    V_ID SEGMERCADO.ID%TYPE := 3;
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacadista';
BEGIN
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    COMMIT;
END;

------EXCLUSAO--------------------
DECLARE
    V_ID SEGMERCADO.ID%TYPE := 5;
BEGIN
    DELETE FROM SEGMERCADO WHERE ID = V_ID;
    COMMIT;
END;

SELECT * FROM SEGMERCADO;