/*Faça um programa em PL/SQL que substitua o - por > 
nos outros dois registros da tabela.
*/

-----PRIMEIRA TENTATIVA, NAO É A MAIS FACIL -------
DECLARE
   v_COD PRODUTO_EXERCICIO.COD%TYPE := '41232';
   v_DESCRICAO PRODUTO_EXERCICIO.DESCRICAO%TYPE := 'Sabor de Verão - Laranja - 1 Litro';
   --v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE := 'Sucos de Frutas';
BEGIN
    UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO, '-', '>')
    WHERE COD = V_COD;
   COMMIT;
END;

------SEGUNDA TENTATIVA, ATUALIZANDO APENAS COM O ID E O REPLACE
DECLARE
   v_COD PRODUTO_EXERCICIO.COD%TYPE := '41232';
BEGIN
    UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE((
    SELECT DESCRICAO FROM PRODUTO_EXERCICIO
    WHERE COD = V_COD), '-', '>')
    WHERE COD = V_COD;
    COMMIT;
END;

SELECT * FROM PRODUTO_EXERCICIO;

------OUTRA OPCAO
DECLARE
BEGIN
UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO, '-', '>');
COMMIT;
END;