--PERMITINDO O USUARIO INSERIR E ALTERAR TABELAS, DANDO UM VALOR ILIMITADO DE TAMANHO AO USUARIO
--NA TABLESPACE, PARA QUE POSSA UTILIZAR UMA COTA ILIMITADA
--USAR NESTE CASO A MAQUINA LOCAL, QUE É O USUARIO SUPER 
--ABAIXO O COMANDO DE ABSTRACAO DO ORACLE
ALTER USER cursoplsql QUOTA UNLIMITED ON USERS;