/*Modifique a rotina acima de tal maneira que:
1) O valor da venda será a quantidade * preco.
2) O percentual do imposto será obtido da função RETORNA_IMPOSTO, implementada na atividade anterior.
Depois inclua nova venda com apenas os seguintes dados:
ID: 2
COD_PRODUTO: 92347
DATA: 1/1/2022
QUANTIDADE: 200
PRECO: 25
*/

CREATE OR REPLACE PROCEDURE INCLUINDO_DADOS_VENDA
    (
    P_ID  PRODUTO_VENDA_EXERCICIO.ID%TYPE,
    P_COD PRODUTO_VENDA_EXERCICIO.COD_PRODUTO%TYPE,
    P_DATA  PRODUTO_VENDA_EXERCICIO.DATA%TYPE,
    P_QUANTIDADE  PRODUTO_VENDA_EXERCICIO.QUANTIDADE%TYPE,
    P_PRECO  PRODUTO_VENDA_EXERCICIO.PRECO%TYPE
    )
IS
    V_VALOR  PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
    V_PERCENTUAL PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE;
BEGIN
    V_VALOR := RETORNA_VALOR2(P_QUANTIDADE, P_PRECO);
    --OUTRA FROMA DE FAZER SEM USAR FUNCAO---------
    --V_VALOR := P_QUANTIDADE * P_PRECO;
    V_PERCENTUAL := RETORNA_IMPOSTO(P_COD);

    INSERT INTO PRODUTO_VENDA_EXERCICIO
    VALUES
    (
    P_ID,
    P_COD,
    P_DATA,
    --SYSDATE,
    P_QUANTIDADE,
    P_PRECO,
    V_VALOR,
    V_PERCENTUAL
    );    
    COMMIT;
END;

SELECT * FROM PRODUTO_VENDA_EXERCICIO;
SELECT * FROM PRODUTO_EXERCICIO;

EXECUTE INCLUINDO_DADOS_VENDA(2, '92347', '01/01/2022', 200, 25);

