
DECLARE
    V_ID SEGMERCADO.ID%TYPE := 4;
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
BEGIN
    INSERT INTO SEGMERCADO (ID,DESCRICAO) VALUES(V_ID, UPPER(V_DESCRICAO));
    COMMIT;
END;

SELECT* FROM SEGMERCADO;

SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'Atacado';
SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'atacado';

SELECT * FROM SEGMERCADO WHERE UPPER(DESCRICAO) = 'ATACADO';

DELETE FROM SEGMERCADO WHERE ID = '4';