ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CRIANDO USUARIO E IDENTIFIED SENHA 
CREATE USER cursoplsql2 IDENTIFIED BY cursoplsql2 DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE TO cursoplsql2;

ALTER USER cursoplsql2 QUOTA UNLIMITED ON USERS;