CREATE OR REPLACE FUNCTION OBTER_DESCRICAO_SEGMERCADO
    (P_ID IN SEGMERCADO.ID%TYPE)
RETURN
    SEGMERCADO.DESCRICAO%TYPE --RETORNA UM TIPO DA TABELA SEGMERCADO VARCHAR2
IS
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    SELECT DESCRICAO INTO V_DESCRICAO FROM SEGMERCADO WHERE ID = P_ID;
    RETURN V_DESCRICAO;
END;


-------------USANDO A FUNCAO------------
--EX DESCRICAO LOWER E DA FUNCAO CRIADA
SELECT ID, DESCRICAO,LOWER(DESCRICAO) FROM SEGMERCADO WHERE ID =1;

--SEM USAR O WHERE
SELECT ID, DESCRICAO,LOWER(DESCRICAO) FROM SEGMERCADO;