--RETORNA O VALOR = PRECO * QUANTIDADE DA TABELA PRODUTO_VENDA_EXERCICIO
CREATE OR REPLACE FUNCTION RETORNA_VALOR2
    (
    --P_ID IN PRODUTO_VENDA_EXERCICIO.ID%TYPE,
    P_QUANTIDADE IN PRODUTO_VENDA_EXERCICIO.QUANTIDADE%TYPE,
    P_PRECO IN PRODUTO_VENDA_EXERCICIO.PRECO%TYPE
    )
RETURN 
   PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE
IS
    V_VALOR PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;    
BEGIN
    V_VALOR := P_QUANTIDADE * P_PRECO;
    RETURN V_VALOR;
END;

--VERIFICAR CODIGOS_ PRODUTO-----------
SELECT * FROM PRODUTO_VENDA_EXERCICIO;

-----EXECUTAR FUNCAO PARA TESTE-------------------------------
DECLARE
    QUANTIDADE FLOAT;
    PRECO FLOAT;
    TOTAL FLOAT;
  BEGIN
    QUANTIDADE := 100;
    PRECO := 10;
    TOTAL := RETORNA_VALOR2(QUANTIDADE, PRECO);
    dbms_output.put_line('VALOR TOTAL = ' || TOTAL);
END;

------RESUMO----------------
SET SERVEROUTPUT ON

DECLARE
    TOTAL FLOAT;
  BEGIN
    TOTAL := RETORNA_VALOR2(100, 10);
    dbms_output.put_line('VALOR TOTAL = ' || TOTAL);
END;