VARIABLE G_DESCRICAO VARCHAR2(100);
EXECUTE : G_DESCRICAO:= OBTER_DESCRICAO_SEGMERCADO(3);
PRINT G_DESCRICAO;

SET SERVEROUTPUT ON
DECLARE
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
    V_ID SEGMERCADO.ID%TYPE := 1;
BEGIN
    V_DESCRICAO:= OBTER_DESCRICAO_SEGMERCADO(V_ID);
    dbms_output.put_line('A DESCRICAO DO SEGMENTO É ' || V_DESCRICAO);
END;

variable v_saida varchar2(100);
execute : v_saida := obter_descricao_segmercado(3);
print v_saida;