--INSERT MAS PRECISA ALTERAR A PERMISSAO DO USUARIO ANTES
INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (1, 'VAREJO');


--EXCLUINDO A TABELA PARA CRIAR POR PL/SQL
DELETE FROM SEGMERCADO;

--VISUALIZANDO A TABELA
SELECT * FROM SEGMERCADO;

--PL/SQL----------------------------------------------------------
DECLARE
    V_ID NUMBER(5) := 2;
    V_DESCRICAO VARCHAR2(100) := 'Industria';
BEGIN
    INSERT INTO SEGMERCADO (ID,DESCRICAO) VALUES(V_ID, V_DESCRICAO);
    COMMIT;
END;