--pequeno até 10000
--medio 10001 ate 50000
--medio grande 50001 ate 100000
--grande acima de 100000

SET SERVEROUTPUT ON

DECLARE
    V_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE:= 5000;
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF V_FATURAMENTO <= 10000 THEN
        V_CATEGORIA := 'PEQUENO';
    ELSIF V_FATURAMENTO <= 50000 THEN
        V_CATEGORIA := 'MEDIO';
    ELSIF V_FATURAMENTO <= 100000 THEN
        V_CATEGORIA := 'MEDIO GRANDE';
    ELSE
        V_CATEGORIA := 'GRANDE';
    END IF;
    dbms_output.put_line('A categoria é ' || V_CATEGORIA);
END;