--PERCENT TYPE, DEFINIR O MESMO TIPO DA TABELA SEM PRECISAR DEFINIR IGUALMENTE
--USAMOS O PERCENT TYPE %TYPE
SELECT* FROM SEGMERCADO;

DECLARE
    V_ID SEGMERCADO.ID%TYPE := 3;
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
BEGIN
    INSERT INTO SEGMERCADO (ID,DESCRICAO) VALUES(V_ID, V_DESCRICAO);
    COMMIT;
END;