/*
QUANDO SABEMOS A QUANTIDADE, USAMOS O FOR. A PREMISSA PRINCIPAL É QUE OS IDS SEAM SEQUENCIAIS
SE ALTERAR A ORDEM DO ID NO EXEMPLO INICIAL, ELE NAO ALTERA O VALOR DO ID 30 POR EXEMPLO;
É NECESSÁRIO COLOCAR OD IDS EM UM VETOR, SENDO ASSIM A ALTERACAO SERÁ POR VETOR E NAO POR
CONTADOR;
*/
DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 3;
    V_ID CLIENTE.ID%TYPE;
    CURSOR CUR_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN CUR_CLIENTE;
    
    LOOP
        FETCH CUR_CLIENTE INTO V_ID;  
    --CASO O FETCH(CURSOR) CHEGUE AO FINAL ELE SAI E NAO ATUALIZA;
    EXIT WHEN CUR_CLIENTE%NOTFOUND;
        ATUALIZAR_SEGMERCADO(P_SEGMERCADO_ID => V_SEGMERCADO, P_ID => V_ID);
    END LOOP;
    CLOSE CUR_CLIENTE;
COMMIT;
END;


SELECT * FROM CLIENTE;