/*
QUANDO SABEMOS A QUANTIDADE, USAMOS O FOR. A PREMISSA PRINCIPAL É QUE OS IDS SEAM SEQUENCIAIS
SE ALTERAR A ORDEM DO ID NO EXEMPLO INICIAL, ELE NAO ALTERA O VALOR DO ID 30 POR EXEMPLO;
É NECESSÁRIO COLOCAR OD IDS EM UM VETOR, SENDO ASSIM A ALTERACAO SERÁ POR VETOR E NAO POR
CONTADOR;
*/
DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 1;
    V_NUMCLI INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_NUMCLI FROM CLIENTE;
    FOR V_ID IN 1..V_NUMCLI LOOP
    ----UTILIZA OS NOMES DOS PARAMETROS DA PROCEDURE ATUALIZAR_SEGMERCADO
    ----PARA NAO PRECISAR UTILIZAR A ORDEM DE ENTRADA DOS PARAMETROS;
        ATUALIZAR_SEGMERCADO(P_SEGMERCADO_ID => V_SEGMERCADO, P_ID => V_ID);
    END LOOP;
END;

SELECT * FROM CLIENTE ORDER BY ID;

EXECUTE INCLUIR_CLIENTE(30, 'Loja MM', '56854960854906', 2, 60000);