SELECT * FROM CLIENTE;

--CONCEITO DE LOOP FOR;
DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 4;
    --V_ID CLIENTE.ID%TYPE := 1; --QUANDO DECLARADO NO FOR, NAO PRECISA SER DECLARADO AQUI
    V_NUMCLI INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_NUMCLI FROM CLIENTE;
    
    FOR V_ID IN 1..V_NUMCLI LOOP
        ATUALIZAR_SEGMERCADO (V_ID, V_SEGMERCADO);
    END LOOP;    
END;