DECLARE
   V_PRODUTO PRODUTO_EXERCICIO.COD%TYPE:= 41232;
   E_RES_INT EXCEPTION;
   PRAGMA EXCEPTION_INIT(E_RES_INT, -2292);
BEGIN
   EXCLUINDO_PRODUTO(V_PRODUTO);
EXCEPTION
    WHEN E_RES_INT THEN
    RAISE_APPLICATION_ERROR(-20020, 'O IDENTIFICADOR POSSUI VENDA, NAO PODE SER EXCLUIDO');
END;

--tabelas pai e filho do produto 41232
SELECT * FROM PRODUTO_EXERCICIO;
SELECT * FROM PRODUTO_VENDA_EXERCICIO;