--CRIACAO DA TABELA
CREATE TABLE TAB_FETCH
(ID INTEGER, NOME VARCHAR(10), VALOR VARCHAR(10));

--INSERCAO DE DADOS
INSERT INTO TAB_FETCH VALUES (1,'PRODUTO1',10);
INSERT INTO TAB_FETCH VALUES (2,'PRODUTO2',10);
INSERT INTO TAB_FETCH VALUES (3,'PRODUTO3',10);
INSERT INTO TAB_FETCH VALUES (4,'PRODUTO4',10);
INSERT INTO TAB_FETCH VALUES (5,'PRODUTO5',10);
INSERT INTO TAB_FETCH VALUES (6,'PRODUTO6',10);
INSERT INTO TAB_FETCH VALUES (7,'PRODUTO7',10);
INSERT INTO TAB_FETCH VALUES (8,'PRODUTO8',10);
INSERT INTO TAB_FETCH VALUES (9,'PRODUTO9',10);

SELECT * FROM TAB_FETCH;
COMMIT;

--PLSQL COM CURSOR-------------------------------
SET SERVEROUTPUT ON;
DECLARE 
    V_NOME VARCHAR2(10);
    V_VALOR FLOAT;
    V_VALOR_ACUMULATIVO FLOAT := 0;
    CURSOR CURSOR1 IS SELECT NOME, VALOR FROM TAB_FETCH WHERE MOD(ID,2) = 0;
BEGIN
    OPEN CURSOR1;
        
    WHILE V_VALOR_ACUMULATIVO < 30 LOOP
        FETCH CURSOR1 INTO V_NOME, V_VALOR;
        V_VALOR_ACUMULATIVO :=   V_VALOR + V_VALOR_ACUMULATIVO;
        --dbms_output.put_line(V_NOME || '    '||V_VALOR_ACUMULATIVO);        
    END LOOP;
     dbms_output.put_line(V_NOME);
    CLOSE CURSOR1;    
END;




