DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 3;
    V_ID CLIENTE.ID%TYPE;
    CURSOR CUR_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN CUR_CLIENTE;
    --O FETCH É NECESSARIO PARA INICIALIZAR A VARIAVEL DO CUR_CLIENTE;
    FETCH CUR_CLIENTE INTO V_ID; 
    
    WHILE CUR_CLIENTE%FOUND LOOP
        ATUALIZAR_SEGMERCADO(P_SEGMERCADO_ID => V_SEGMERCADO, P_ID => V_ID);
        FETCH CUR_CLIENTE INTO V_ID;         
    END LOOP;
    CLOSE CUR_CLIENTE;
COMMIT;
END;


SELECT * FROM CLIENTE;