SET SERVEROUTPUT ON;

DECLARE
    V_ID CLIENTE.ID%TYPE;
    V_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE;
    CURSOR CUR_CLIENTE IS SELECT ID, RAZAO_SOCIAL FROM CLIENTE;
BEGIN
    OPEN CUR_CLIENTE;

    LOOP
        FETCH CUR_CLIENTE INTO V_ID, V_RAZAO;
    --QUANDO O CURSOR CHEGAR AO FINAL E NAO ENCONTRAR MAIS REGISTROS
    EXIT WHEN CUR_CLIENTE%NOTFOUND;
    dbms_output.put_line('ID = ' || V_ID || ', RAZAO = ' || V_RAZAO);
    END LOOP;
END;