CREATE OR REPLACE PROCEDURE SOMA_VENDAS_CURSOR_EXERCICIO
    (
    P_VENDA_LIMITE IN PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE, 
    P_ID_RETORNO OUT PRODUTO_VENDA_EXERCICIO.ID%TYPE
    )
IS
    V_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE;
    V_VALOR_TOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
    V_VENDA_TOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE := 0;
    CURSOR CUR_VALOR_TOTAL IS SELECT  ID, VALOR_TOTAL  FROM PRODUTO_VENDA_EXERCICIO; --ORDER BY ID ASC;
BEGIN
    OPEN CUR_VALOR_TOTAL;
    
    LOOP
        FETCH CUR_VALOR_TOTAL INTO V_ID, V_VALOR_TOTAL;
      
        V_VENDA_TOTAL := V_VENDA_TOTAL + V_VALOR_TOTAL;
        IF V_VENDA_TOTAL >= P_VENDA_LIMITE THEN
            EXIT;
        END IF;
   END LOOP;
   P_ID_RETORNO := V_ID;
   CLOSE CUR_VALOR_TOTAL;
END;


SET SERVEROUTPUT ON;
DECLARE
    V_ENTRADA PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE := 20000;
    V_SAIDA PRODUTO_VENDA_EXERCICIO.ID%TYPE;
BEGIN
    SOMA_VENDAS_CURSOR_EXERCICIO(V_ENTRADA, V_SAIDA);
    dbms_output.put_line(V_SAIDA);
END;



SELECT * FROM PRODUTO_VENDA_EXERCICIO; --ORDER BY ID ASC;