DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 1;
    CURSOR CUR_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    --FOR NAO PRECISA DO %NOTFOUND OU SEJA TESTAR O CUR_CLIENTE
    --TAMBEM ABRE E FECHA O CURSOR
    FOR LINHA_CUR_CLIENTE IN CUR_CLIENTE LOOP
        ATUALIZAR_SEGMERCADO(LINHA_CUR_CLIENTE.ID, V_SEGMERCADO);
    END LOOP;
COMMIT;
END;

SELECT * FROM CLIENTE;