SET SERVEROUTPUT ON;

DECLARE
    V_CNPJ CLIENTE.CNPJ%TYPE;
    V_CNPJ_SAIDA CLIENTE.CNPJ%TYPE;
BEGIN
    V_CNPJ := '1234567890';
    V_CNPJ_SAIDA := '1234567890'; -- V_CNPJ_SAIDA := V_CNPJ;
    dbms_output.put_line('SEM FORMATACAO: ' || V_CNPJ|| '   ' || V_CNPJ_SAIDA);
    FORMATA_CNPJ(V_CNPJ, V_CNPJ_SAIDA);
    dbms_output.put_line('COM FORMATACAO: ' || V_CNPJ|| '   ' || V_CNPJ_SAIDA);
END;

