SELECT * FROM CLIENTE;

EXECUTE INCLUIR_CLIENTE(16, 'CLIENTE NOVO 3', '5498695486', 1, 90000);

EXECUTE INCLUIR_CLIENTE(15, 'CLIENTE NOVO 2', '5498695486', 1, 70000);

/*
A função raise_application_error faz com que eu crie um erro 
customizado no formato de um erro Oracle. 
Eu passo dois parâmetros: o número do erro e o texto do erro
de -20000 -20999. 
*/

CREATE OR REPLACE NONEDITIONABLE PROCEDURE INCLUIR_CLIENTE
(
P_ID CLIENTE.ID%TYPE,
P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
P_CNPJ CLIENTE.CNPJ%TYPE,
P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE
)
IS
  V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
  V_CNPJ CLIENTE.CNPJ%TYPE; --FOI CRIADO DEVIDO AO FORMATA CNPJ TER ENTRADA E SAIDA DE DADOS IN E OUT
BEGIN

   V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);
   FORMATA_CNPJ(P_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (P_ID, P_RAZAO, V_CNPJ, P_SEGMERCADO, SYSDATE, P_FATURAMENTO, V_CATEGORIA);

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JÁ CADASTRADO!!!');
   COMMIT;
   
END;