/*
CONSTRUIR UMA PROCEDURE QUE POSSA ALTERAR O SEGMERCADO
PARAMETRO ID
*/
SELECT * FROM CLIENTE;

EXECUTE INCLUIR_CLIENTE(5, 'MERCEARIA XYZ', '9998885556', 1, 10000);
EXECUTE INCLUIR_CLIENTE(6, 'FARMACIA ABC', '9998845556', 1, 10000);
EXECUTE INCLUIR_CLIENTE(7, 'MERCADINHO RUA BORBOREMA', '9998335556', 1, 10000);
EXECUTE INCLUIR_CLIENTE(8, 'TAVERNA POI', '9998775556', 1, 10000);
EXECUTE INCLUIR_CLIENTE(9, 'XURASCO DO XULIO', '9998445556', 1, 10000);


--------------PROCEDURE ------------------
CREATE OR REPLACE PROCEDURE ATUALIZAR_SEGMERCADO
    (
    P_ID CLIENTE.ID%TYPE,
    P_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE
    )
IS
BEGIN
    UPDATE CLIENTE SET SEGMERCADO_ID = P_SEGMERCADO_ID
    WHERE ID = P_ID;
    COMMIT;
END;


-----TESTE DA ROCEDURE------------
SELECT * FROM CLIENTE;
SELECT * FROM SEGMERCADO;
/*
TROCAR O SEGMENTO DE MERCADO DE 1 PARA 2
*/
EXECUTE ATUALIZAR_SEGMERCADO(1,3);
EXECUTE ATUALIZAR_SEGMERCADO(2,3);
EXECUTE ATUALIZAR_SEGMERCADO(3,3);
EXECUTE ATUALIZAR_SEGMERCADO(4,3);