CREATE OR REPLACE PROCEDURE NUMEROS_FIBONACCI_FOR_INSTRUTOR (p_INTERACOES IN FLOAT, p_NUMEROFIBO OUT FLOAT)
IS
   v_FIBO1 FLOAT := 0;
   v_FIBO2 FLOAT := 1;
   v_FIBO_ATUAL FLOAT := 0;
BEGIN
   IF p_INTERACOES > 1 THEN
      FOR v_CONTADOR IN 2..p_INTERACOES LOOP
         v_FIBO_ATUAL := v_FIBO1 + v_FIBO2;
         v_FIBO1 := v_FIBO2;
         v_FIBO2 := v_FIBO_ATUAL;
      END LOOP;
   END IF;
   p_NUMEROFIBO := v_FIBO_ATUAL;
END;

-----------TESTE----------------------------
DECLARE
    V_VALOR NUMBER;
    V_VALOR_SAIDA NUMBER;
BEGIN
    V_VALOR := 45;
    NUMEROS_FIBONACCI_FOR_INSTRUTOR(V_VALOR, V_VALOR_SAIDA);
   dbms_output.put_line('Resultado: ' || V_VALOR_SAIDA);
END;