SELECT * FROM CLIENTE;

-- EXEMPLO APENAS 123/45-67890

SELECT CNPJ, SUBSTR(CNPJ,1,3) || '/' || SUBSTR(CNPJ,4,2) || '-' || SUBSTR(CNPJ,6) AS CNPJ_FORMATADO 
FROM CLIENTE;

--APENAS O CNPJ FORMATADO
SELECT SUBSTR(CNPJ,1,3) || '/' || SUBSTR(CNPJ,4,2) || '-' || SUBSTR(CNPJ,6) AS CNPJ_FORMATADO 
FROM CLIENTE;