/*
CRIACAO DO LOOP
*/

SELECT * FROM CLIENTE;

--CONCEITO DE LOOP;
DECLARE
    V_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 3;
    V_ID CLIENTE.ID%TYPE := 1;
BEGIN
    LOOP
        ATUALIZAR_SEGMERCADO (V_ID, V_SEGMERCADO);
        V_ID := V_ID +1;
    EXIT WHEN V_ID > 9;
    END LOOP;
END;