SELECT * FROM CLIENTE;

--ERRO NULO
EXECUTE INCLUIR_CLIENTE(NULL, 'CLIENTE NOVO 3', '5498695486', 1, 90000);

EXECUTE INCLUIR_CLIENTE(15, 'CLIENTE NOVO 2', '5498695486', 1, 70000);

--ERRO NAO ESPERADO, SEGMENTO NAO EXISTE
EXECUTE INCLUIR_CLIENTE(18, 'CLIENTE NOVO 4', '5498695486', 6, 70000);

--ERRO NAO ESPERADO, SEGMENTO NAO EXISTE
EXECUTE INCLUIR_CLIENTE(18, 'CLIENTE NOVO 4', '5498695486', 7, 70000);

--ERRO NAO ESPERADO, TAMANHO DO CAMPO
EXECUTE INCLUIR_CLIENTE(18, 'CLIENTE NOVO RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', '5498695486', 6, 70000);
/*
A função raise_application_error faz com que eu crie um erro 
customizado no formato de um erro Oracle. 
Eu passo dois parâmetros: o número do erro e o texto do erro
de -20000 -20999. 
*/

CREATE OR REPLACE NONEDITIONABLE PROCEDURE INCLUIR_CLIENTE
(
P_ID CLIENTE.ID%TYPE,
P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
P_CNPJ CLIENTE.CNPJ%TYPE,
P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE
)
IS
  V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
  V_CNPJ CLIENTE.CNPJ%TYPE; --FOI CRIADO DEVIDO AO FORMATA CNPJ TER ENTRADA E SAIDA DE DADOS IN E OUT
  --CRIACAO DO NOME AMIGAVEL PARA EXCECOES QUE NAO EXISTEM NA LISTA EXCEPTION ORACLE
  --CRIACAO DE VARIAVEL EXCEPTION
  E_ID_NULO EXCEPTION;
  --DETERMINANDO QUE A EXCEPTION VAI CRIAR A EXCESSAO COM O ERRO ORA-01400
  PRAGMA EXCEPTION_INIT(E_ID_NULO, -1400);
BEGIN

   V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);
   FORMATA_CNPJ(P_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (P_ID, P_RAZAO, V_CNPJ, P_SEGMERCADO, SYSDATE, P_FATURAMENTO, V_CATEGORIA);

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JÁ CADASTRADO!!!');
    WHEN E_ID_NULO THEN
        RAISE_APPLICATION_ERROR(-20015, 'IDENTIFICADOR DO CLIENTE NULO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20020, 'ERRO NÃO ESPERADO - TEXTO ORIGINAL DO ORACLE '|| SQLERRM());
   COMMIT;
   
END;