/*
Crie uma procedure que, dado um identificador da venda (ID ), 
da tabela PRODUTO_VENDA_EXERCICIO, temos como retorno o valor financeiro 
do imposto. O parâmetro referente ao resultado do imposto deve ser passado 
para essa procedure como um parâmetro OUT.

A fórmula do imposto será:

(PRECO * VALOR_TOTAL)*(PERCENTUAL_IMPOSTO/100)
Chame essa procedure de CALCULO_IMPOSTO.

FORMA CORRETA
(PRECO * QUANTIDADE)*(PERCENTUAL_IMPOSTO/100)
*/

SELECT * FROM PRODUTO_VENDA_EXERCICIO;

-- BASE DA FUNCAO OU PROCEDURE >> ID1 = 10000, ID2 = 18750
SELECT ((PRECO * QUANTIDADE) *(PERCENTUAL_IMPOSTO / 100)) AS CALCULO_IMPOSTO
FROM PRODUTO_VENDA_EXERCICIO
WHERE ID = 1;

---------PROCEDURE ---------------------------------------- 
CREATE OR REPLACE PROCEDURE CALCULO_IMPOSTO
    (
    P_ID IN PRODUTO_VENDA_EXERCICIO.ID%TYPE,
    P_CALCULO OUT PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE
    )
IS
BEGIN
    --SELECT ((PRECO * VALOR_TOTAL) *(PERCENTUAL_IMPOSTO / 100)) AS CALCULO_IMPOSTO INTO P_CALCULO 
    SELECT ((PRECO * QUANTIDADE) *(PERCENTUAL_IMPOSTO / 100)) AS CALCULO_IMPOSTO INTO P_CALCULO
    FROM PRODUTO_VENDA_EXERCICIO
    WHERE ID = P_ID;
    COMMIT;
END;

--------------VERIFICACAO DA PROCEDURE------------------------------
SET SERVEROUTPUT ON;
DECLARE
    V_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE;
    V_CALCULO PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
BEGIN
    V_ID := 2;
    CALCULO_IMPOSTO(V_ID, V_CALCULO);
    dbms_output.put_line('ID: '|| V_ID ||' >> CALCULO DO IMPOSTO: ' || V_CALCULO);
END;