SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

SELECT DISTINCT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

-- QUANDO UTILIZA O GROUP BY, O CAMPO QUE ESTÁ COMO AGREGACAO NAO PODERA SER UTILIZADO NO ORDER BY
SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;

SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE)  FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

-- QUANDO USA AGREGACAO É NECESSARIO O GROUP BY
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM;

-- CONTA OS GRUPOS (TODOS) DO GRUPO EMBALAGEM
SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS "NUMERO DE PRODUTOS" FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM ORDER BY EMBALAGEM DESC;

SELECT EMBALAGEM, NOME_DO_PRODUTO  AS "NUMERO DE PRODUTOS" FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM,NOME_DO_PRODUTO ORDER BY EMBALAGEM DESC;
