--QUAL SERA O RESULTADO DO COMIIT E ROLLBACK ABAIXO?

CREATE TABLE TAB_TRANSACAO (CAMPO INTEGER);
INSERT INTO TAB_TRANSACAO VALUES (1);
INSERT INTO TAB_TRANSACAO VALUES (2);
INSERT INTO TAB_TRANSACAO VALUES (3);
COMMIT;

SELECT * FROM TAB_TRANSACAO;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 1;
INSERT INTO TAB_TRANSACAO VALUES (4);
ROLLBACK;

SELECT * FROM TAB_TRANSACAO;
INSERT INTO TAB_TRANSACAO VALUES (1);
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 2;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 3;
COMMIT;

SELECT * FROM TAB_TRANSACAO;
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 1;
INSERT INTO TAB_TRANSACAO VALUES (1);
INSERT INTO TAB_TRANSACAO VALUES (2);
DELETE FROM TAB_TRANSACAO WHERE CAMPO = 4;
COMMIT;

SELECT * FROM TAB_TRANSACAO;
INSERT INTO TAB_TRANSACAO VALUES (3);
INSERT INTO TAB_TRANSACAO VALUES (4);
ROLLBACK;