--COPIA OS VALORES E CAMPOS DA TABELA PRODUTOS
CREATE TABLE PRODUTOS2 AS (SELECT * FROM PRODUTOS);

SELECT * FROM PRODUTOS2;

UPDATE PRODUTOS2 SET PRECO_LISTA = 8;

--SALVANDO OS SCRIPTS E ALTERACOES
COMMIT;

--ESTE CODIGO NAO SERÁ SALVO
UPDATE PRODUTOS2 SET PRECO_LISTA = 7;
--O ROLLBACK, SERÁ RETORNADO ATÉ A ÚLTIMA ALTERAçAO ANTES DO COMMIT
ROLLBACK;