/*
Nesta aula, construímos um relatório que apresentou os clientes que tiveram vendas inválidas. Complemente este relatório, listando somente os que tiveram vendas inválidas e calculando a diferença entre o limite de venda máximo e o realizado, em percentuais. Dica:
Capture a SQL final da aula;
Filtre somente as linhas onde:
(VOLUME_DE_COMPRA - QUANTIDADE_VENDAS) < 0
Liste a coluna VOLUME_DE_COMPRA;
Crie uma nova coluna, fazendo a fórmula:
(1 - (VOLUME_DE_COMPRA/QUANTIDADE_VENDAS)) * 100
*/

--VERIFICANDO E COLOCANDO CONDICAO
SELECT 
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.QUANTIDADE_TOTAL,TV.MES_ANO,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDA VÁLIDA'
     ELSE 'VENDA INVÁLIDA' END) AS VERIFICACAO, ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100, 2) AS "INDICADOR"
FROM TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
N.CPF, TO_CHAR(N.DATA_VENDA, 'MM-YYYY') AS "MES_ANO", 
SUM(I.QUANTIDADE) AS "QUANTIDADE_TOTAL"
FROM
NOTAS_FISCAIS N
INNER JOIN
ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
GROUP BY  CPF, TO_CHAR(N.DATA_VENDA, 'MM-YYYY')) TV
ON TV.CPF = TC.CPF
--VERIFICAR APENAS POR MES
WHERE  TV.MES_ANO = '02-2015' and (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0 ;


---RESOLUCAO INSTRUTOR
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100,2)
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '02-2015'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;


---MINHA TENTATIVA DE SIMPLIFICACAO----------TEVE QUE USAR O HAVING DEVIDO A FUNCAO DE GRUPO SUM(I.QUANTIDADE) < 0-------------------------
SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA ,SUM(I.QUANTIDADE) QUANTIDADE_TOTAL, TO_CHAR(N.DATA_VENDA, 'MM-YYYY') AS "MES_ANO",
(CASE WHEN TC.VOLUME_DE_COMPRA >= SUM(I.QUANTIDADE) THEN 'VENDA VÁLIDA'
     ELSE 'VENDA INVÁLIDA' END) AS VERIFICACAO, 
     ROUND((1 - (TC.VOLUME_DE_COMPRA/SUM(I.QUANTIDADE))) * 100, 2) AS "INDICADOR"
FROM NOTAS_FISCAIS N, ITENS_NOTAS_FISCAIS I, TABELA_DE_CLIENTES TC
WHERE  (N.NUMERO = I.NUMERO AND TC.CPF = N.CPF) AND TO_CHAR(N.DATA_VENDA, 'MM-YYYY') = '02-2015' 
GROUP BY  TC.NOME, TC.CPF, TC.VOLUME_DE_COMPRA, TO_CHAR(N.DATA_VENDA, 'MM-YYYY')
HAVING TC.VOLUME_DE_COMPRA - SUM(I.QUANTIDADE) < 0
ORDER BY TC.NOME;

