ALTER TABLE TAB_FUNCIONARIO
ADD CONSTRAINT FK_DEPARTAMENTO
FOREIGN KEY(COD_DEPARTAMENTO) 
REFERENCES TAB_DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE TAB_DEPENDENTE
ADD CONSTRAINT FK_FUNCIONARIO
FOREIGN KEY(COD_FUNCIONARIO) 
REFERENCES TAB_FUNCIONARIO(COD_FUNCIONARIO);