CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10)NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
CONSTRAINT PK_COD_PROD PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50),
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS INTEGER NULL,
CONSTRAINT PK_MAT_VEND PRIMARY KEY(MATRICULA)
);

--RENOMEAR COLUNA DE UMA TABELA--
ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;