--CRIANDO UM NOVO AMBIENTE DE TRABALHO NO USUÁRIO  MASTER, NESTE CASO CONEXAO MAQUINA LOCAL
 --O NOME DA VARIAVEL EM ASPAS DUPLAS PRECISA SER EM LETRA MAISCULA
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; --VERDADEIRO PARA CONEXAO E PARA DAR ACESSO AOS USUARIOS

--AO INSTALAR O ORACLE USAMOS O USER SYSTEM - USUARIO MASTER
--ABAIXO CRIANDO O NOVO USUARIO COM SENHA E LOGIN
--TABLESPACE O TAMANHO POR USUARIO, NESTE CASO O VALOR PADRAO DOS USUARIOS
CREATE USER trust_tab IDENTIFIED BY trust_tab DEFAULT TABLESPACE USERS;

--PRIVILEGIO DE USUARIO
--GRANT PRIVILEGIO DE SEGURANCA_transformando cursoplsql em SUPER USUARIO
GRANT CONNECT, RESOURCE TO trust_tab;

--aPOS ISSO CRIAR A CONEXAO COM AS MESMAS INFORMACOES INSERIDAS NESTE SCRIPT