CREATE TABLE TAB_PLANO_SAUDE
(COD_PLANO VARCHAR(5),
NOME_PROJETO VARCHAR(50),
VALOR FLOAT NOT NULL,
COD_FUNCIONARIO VARCHAR(5),
COD_DEPENDENTE VARCHAR(5),
CONSTRAINT PK_COD_PLANO PRIMARY KEY(COD_PLANO),
CONSTRAINT FK_COD_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES TAB_FUNCIONARIO(COD_FUNCIONARIO),
CONSTRAINT FK_COD_DEPENDENTE FOREIGN KEY(COD_DEPENDENTE) REFERENCES TAB_DEPENDENTE(COD_DEPENDENTE)
);

ALTER TABLE TAB_PLANO_SAUDE
ADD COD_EMPRESA VARCHAR(5);

ALTER TABLE TAB_PLANO_SAUDE
ADD CONSTRAINT FK_COD_EMPRESA FOREIGN KEY(COD_EMPRESA) REFERENCES TAB_EMPRESA(COD_EMPRESA);