CREATE TABLE TAB_EMPRESA
(COD_EMPRESA VARCHAR (5) PRIMARY KEY,
NOME_EMPRESA VARCHAR(50)
);

CREATE TABLE TAB_DEPARTAMENTO
(COD_DEPARTAMENTO VARCHAR(5),
NOME_DEPARTAMENTO VARCHAR(50),
CIDADE_DEPARTAMENTO VARCHAR(50),
COD_EMPRESA VARCHAR(5),
PRIMARY KEY (COD_DEPARTAMENTO)
);

--CRIANDO FOREIGN KEY
ALTER TABLE TAB_DEPARTAMENTO
ADD CONSTRAINT FK_COD_DEP FOREIGN KEY(COD_EMPRESA) 
REFERENCES TAB_EMPRESA(COD_EMPRESA);

CREATE TABLE TAB_PROJETO
(COD_PROJETO VARCHAR(5),
NOME_PROJETO VARCHAR(50),
ORCAMENTO_PROJETO FLOAT,
DATA_INICIO_PROJETO DATE,
COD_DEPARTAMENTO VARCHAR(5),

CONSTRAINT PK_COD_PRO PRIMARY KEY (COD_PROJETO),

CONSTRAINT FK_CODDEPPRO_CODDEPDEP FOREIGN KEY (COD_DEPARTAMENTO) 
REFERENCES TAB_DEPARTAMENTO(COD_DEPARTAMENTO)
);