CREATE TABLE TAB_PROJETO_ORCAMENTO
(cod_projeto VARCHAR(5), percentual_novo_orcamento FLOAT);

INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0001',0.2);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0002',0.1);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0003',-0.1);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0005',0.23);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0007',0.09);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0008',-0.03);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0009',-0.05);
INSERT INTO TAB_PROJETO_ORCAMENTO VALUES ('P0011',0.123);

SELECT * FROM TAB_PROJETO_ORCAMENTO;
SELECT * FROM TAB_PROJETO;

--SELECIONANDO OS CAMPOS DAS DUAS TABELAS
SELECT TP.COD_PROJETO AS COD_PROJETO_TP,
       TPO.COD_PROJETO AS COD_PROJETO_TPO,
       TP.ORCAMENTO AS ORCAMENTO_PROJETO_TP,
       TPO.PERCENTUAL_NOVO_ORCAMENTO AS ORCAMENTO_PROJETO_TPO
FROM
        TAB_PROJETO TP
INNER JOIN 
        TAB_PROJETO_ORCAMENTO TPO
ON TP.COD_PROJETO = TPO.COD_PROJETO;

---USANDO EXISTS
SELECT TP.COD_PROJETO AS COD_PROJETO_TP,
       --TPO.COD_PROJETO AS COD_PROJETO_TPO,
       TP.ORCAMENTO AS ORCAMENTO_PROJETO_TP
       --TPO.PERCENTUAL_NOVO_ORCAMENTO AS ORCAMENTO_PROJETO_TPO
FROM TAB_PROJETO TP
WHERE EXISTS
(SELECT 1 FROM TAB_PROJETO_ORCAMENTO TPO
WHERE TP.COD_PROJETO = TPO.COD_PROJETO);


---FAZENDO A CONTA----
SELECT TP.ORCAMENTO *(1+ (TPO.PERCENTUAL_NOVO_ORCAMENTO)) AS ORCAMENTO_PROJETO_TP,
       TPO.PERCENTUAL_NOVO_ORCAMENTO AS ORCAMENTO_PROJETO_TPO
FROM
        TAB_PROJETO TP
INNER JOIN 
        TAB_PROJETO_ORCAMENTO TPO
ON TP.COD_PROJETO = TPO.COD_PROJETO;


--ATUALIZACAO DOS CAMPOS
UPDATE TAB_PROJETO TP SET TP.ORCAMENTO =  
( 
    SELECT TP.ORCAMENTO * (1 + (TPO.PERCENTUAL_NOVO_ORCAMENTO)) 
    FROM TAB_PROJETO_ORCAMENTO TPO
    WHERE TP.COD_PROJETO = TPO.COD_PROJETO)
WHERE EXISTS(
        SELECT 1 FROM TAB_PROJETO_ORCAMENTO TPO
        WHERE TP.COD_PROJETO = TPO.COD_PROJETO);
        
        
UPDATE TAB_PROJETO
SET ORCAMENTO = 20000
WHERE COD_PROJETO = 'P0001';

--********************TESTES /*****************TESTE ******TESTES****



--TENTATIVA DE CONTA COM O EXISTS
    SELECT TP.ORCAMENTO *(1+ (TPO.PERCENTUAL_NOVO_ORCAMENTO)) AS ORCAMENTO_PROJETO_TP,
       TPO.PERCENTUAL_NOVO_ORCAMENTO AS ORCAMENTO_PROJETO_TPO
FROM
        TAB_PROJETO TP,
        TAB_PROJETO_ORCAMENTO TPO
WHERE EXISTS(
SELECT 1 FROM TAB_PROJETO_ORCAMENTO TPO WHERE TP.COD_PROJETO = TPO.COD_PROJETO);

----APESAR DO TESTE ACIMA DAR O RESULTADO, ESTE EXEMPLO RETORNA MAIS DE UMA 
--LINHA POR ISSO A IMPORTANCIA DO EXISTES
UPDATE TAB_PROJETO TP SET TP.ORCAMENTO = 
(SELECT  TP.ORCAMENTO *(1+ (TPO.PERCENTUAL_NOVO_ORCAMENTO)) AS ORCAMENTO_PROJETO_TP
FROM   TAB_PROJETO TP, TAB_PROJETO_ORCAMENTO TPO
WHERE TP.COD_PROJETO = TPO.COD_PROJETO);