SELECT * FROM NOTAS_FISCAIS;

SELECT * FROM ITENS_NOTAS_FISCAIS;


SELECT RPAD(ROUND(SUM(N.IMPOSTO*(I.QUANTIDADE * I.PRECO))),10,'_')  ||  TO_CHAR(N.DATA_VENDA, 'YYYY') AS "TOTAL_IMPOSTO_|_ANO_IMPOSTO" 
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO
WHERE TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');

-- OPINIAO DO INSTRUTOR
SELECT TO_CHAR(DATA_VENDA, 'YYYY'), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');