SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, PRECO_DE_LISTA, SABOR 
FROM TABELA_DE_PRODUTOS;

--COUNT
SELECT EMBALAGEM, COUNT(*) AS "QUANTIDADE"
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

--AVG
SELECT EMBALAGEM, ROUND(AVG(PRECO_DE_LISTA),2) AS "MEDIA" 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

--MAX E MIN
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS "MAXIMO", MIN(PRECO_DE_LISTA) AS "MINIMO"
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

--SUM
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS "SOMA" 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

--SUM SEM GROUP BY, POR SER APENAS UM CAMPO DE AGREGACAO
SELECT SUM(PRECO_DE_LISTA) AS "SOMA"
FROM TABELA_DE_PRODUTOS;

--GROUP BY SEM AGREGACAO
SELECT EMBALAGEM
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

-- CAMPOS DIFERENTES DA DESCRICAO NO GROUP BY, NAO PERMITEM CONSULTA
SELECT PRECO_DE_LISTA 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;


/*os campos listados na seleção, que não estão em uma função de agregação, 
não são informadas na cláusula group by:*/
SELECT EMBALAGEM, NOME_DO_PRODUTO, AVG(PRECO_DE_LISTA)  
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM; 

/*se utiliza uma função de agregação e campos listados na seleção quando estes 
não estão na função de agregação e não usam uma cláusula group by:*/
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA)   
FROM TABELA_DE_PRODUTOS 
GROUP BY EMBALAGEM ;

/*e nos campos listados na seleção que não estão em uma função de agregação 
e não precisam ser informados na cláusula group by:*/
SELECT EMBALAGEM, NOME_DO_PRODUTO, SUM(PRECO_DE_LISTA) AS "SOMA"
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;