SELECT NOME FROM TABELA_DE_CLIENTES;

-- FORMAS DE INICIAR OS REGISTROS
--CAIXA BAIXA
SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;
--CAIXA BAIXA E ALTA
SELECT NOME, LOWER(NOME), UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;

-- PRIMEIRA LETRA CAIXA ALTA
SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

SELECT ENDERECO_1, BAIRRO FROM TABELA_DE_CLIENTES;

--CONCAT CONCATENA
SELECT ENDERECO_1, BAIRRO, CONCAT(concat(ENDERECO_1,' '),BAIRRO) AS ENDERECO_E_BAIRRO FROM TABELA_DE_CLIENTES;

-- CONCATENACAO
SELECT ENDERECO_1 || ' - ' || BAIRRO || ' - ' || CIDADE ||' - '|| ESTADO AS ENDERECO_COMPLETO FROM TABELA_DE_CLIENTES;

-- COLOCA ESPACO OU * A ESQUERDA DO REGISTRO DE ACORDO COM A QTD
SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 70,'*') FROM TABELA_DE_PRODUTOS;

-- COLOCA ESPACO OU * A DIREITA DO REGISTRO DE ACORDO COM A QTD
SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 70,'*') FROM TABELA_DE_PRODUTOS;

--RETIRA PARTE DA FRASE, A PARTIR DO 3 ELE PEGA 5 A PARTIR DO 3
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS;

--QUEM TIVER 0 NAO TEM E QUEM TIVER MOSTRA A POSICAO DE ONDE ESTA
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO,'Campo') FROM TABELA_DE_PRODUTOS;

/*INSTR PEGA UM VALOR E MOSTRA 0 PRA QUEM NAO TEM O NOME E O 
VALOR REFERENTE A POSICAO DE QUEM TEM*/
SELECT NOME FROM TABELA_DE_CLIENTES;
SELECT NOME, INSTR(NOME,'Mattos') FROM TABELA_DE_CLIENTES;

SELECT NOME FROM TABELA_DE_CLIENTES 
WHERE INSTR(NOME,'Mattos') <> 0;

--LTRIM TIRA ESPACOS A ESQUERDA, DUAL É UMA TABELA QUE NAO EXISTE
SELECT '    MONTEIRO  ' AS X, LTRIM('    MONTEIRO  ') AS Y FROM DUAL;

--RTRIM TIRA ESPACOS DA DIREITA
SELECT '    MONTEIRO  ' AS X, LTRIM('    MONTEIRO  ') AS Y , 
RTRIM('    MONTEIRO  ') AS Z FROM DUAL;

--TRIM TIRA AMBOS OS ESPACOS
SELECT '    MONTEIRO  ' AS X, LTRIM('    MONTEIRO  ') AS Y , 
RTRIM('    MONTEIRO  ') AS Z, TRIM('    MONTEIRO  ') AS T FROM DUAL;

--REPLACE RENOMEIA ALGO
SELECT NOME_DO_PRODUTO,
REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro' , 'L'), 'Ls','L')
FROM TABELA_DE_PRODUTOS;