INSERT INTO PRODUTOS
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES
('1040107', 'Light - 350 ml - Melancia', 'Melancia', '350 ml', 'Lata', 4.6);

INSERT INTO PRODUTOS
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES
('1040108', 'Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 5);


---VRIACOES DE INCLUSAO DE LINHAS -----
INSERT INTO PRODUTOS
VALUES
('1040109', 'Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 3.70);

SELECT * FROM PRODUTOS;

-----INSERINDO VALORES NA TABELA EMPRESA
INSERT INTO TAB_EMPRESA
VALUES
('E0001', 'EMPRESA E0001');
INSERT INTO TAB_EMPRESA
VALUES
('E0002', 'EMPRESA E0002');

SELECT * FROM TAB_EMPRESA;