SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;

SELECT V.MATRICULA AS MATRICULA_VENDEDOR,
       TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES,
       TVF.DE_FERIAS AS FERIAS_FONTE
FROM
        VENDEDORES V
INNER JOIN 
        TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3);

--EXISTS
SELECT V.MATRICULA AS MATRICULA_VENDEDOR,
       V.FERIAS AS FERIAS_VENDEDORES
FROM
        VENDEDORES V
WHERE EXISTS(
        SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
        WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3));
        
--inserindo vendedore e verificando a funcao do exists
INSERT INTO TABELA_DE_VENDEDORES_FONTE
VALUES('00239','Jose Maria', 0.12, TO_DATE('2018-01-01', 'YYYY-MM-DD'), 1, 'Tijuca');

--VERIFICANDO A INSERCAO COM RIGHT JOIN - NAO EXISTE NA TABELA VENDEDORES
SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;
SELECT V.MATRICULA AS MATRICULA_VENDEDOR,
       TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES,
       TVF.DE_FERIAS AS FERIAS_FONTE
FROM
        VENDEDORES V
RIGHT JOIN 
        TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3);

--CONSULTA COM INNER JOIN NAO TRAS 
SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;
SELECT V.MATRICULA AS MATRICULA_VENDEDOR,
       TVF.MATRICULA AS MATRICULA_FONTE,
       V.FERIAS AS FERIAS_VENDEDORES,
       TVF.DE_FERIAS AS FERIAS_FONTE
FROM
        VENDEDORES V
INNER JOIN 
        TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3);