SELECT * FROM VENDEDORES;

SELECT * FROM TAB_PROJETO;

UPDATE TAB_PROJETO
SET NOME_PROJETO = 'PROJETO P0012'
WHERE COD_PROJETO = 'P0012';

DELETE FROM  TAB_PROJETO
WHERE COD_PROJETO = 'P0012';

SELECT * FROM NOTAS;

