/*
Queremos construir um SQL cujo resultado seja, para cada cliente:
O cliente NOME DO CLIENTE faturou QUANTIDADE no ano de ANO
Faça isso somente para o ano de 2016.
*/
select * from tabela_de_clientes;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

--PRIMEIRA TENTATIVA
SELECT C.NOME, SUM(SUB_SEL.TOTAL) AS "FATURAMENTO", SUM(SUB_SEL.QUANTIDADE) AS "QUANTIDADE", SUB_SEL.ANO 
FROM TABELA_DE_CLIENTES C
INNER JOIN
(SELECT (I.QUANTIDADE * I.PRECO) AS "TOTAL", I.QUANTIDADE, I.NUMERO, N.CPF, TO_CHAR(N.DATA_VENDA, 'YYYY') AS "ANO"
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO) SUB_SEL 
ON C.CPF = SUB_SEL.CPF
WHERE SUB_SEL.ANO = 2016
GROUP BY C.NOME, SUB_SEL.ANO
ORDER BY C.NOME;

--SEGUNDA TENTATIVA
SELECT SUB_SEL.CPF, C.NOME, SUB_SEL.FATURAMENTO, SUB_SEL.TOTAL, SUB_SEL.ANO 
FROM TABELA_DE_CLIENTES C
INNER JOIN
(SELECT N.CPF, SUM(I.QUANTIDADE * I.PRECO) AS "FATURAMENTO",
SUM(I.QUANTIDADE) AS "TOTAL", TO_CHAR(N.DATA_VENDA, 'YYYY') AS "ANO"
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO
GROUP BY N.CPF,TO_CHAR(N.DATA_VENDA, 'YYYY')) SUB_SEL 
ON C.CPF = SUB_SEL.CPF
WHERE SUB_SEL.ANO = 2016
ORDER BY C.NOME;

--VERIICACAO DA QUERY - N.CPF = '50534475787' = 'ABEL SILVA'
SELECT N.CPF, SUM(I.QUANTIDADE * I.PRECO) AS "FATURAMENTO",
SUM(I.QUANTIDADE) AS "TOTAL", TO_CHAR(N.DATA_VENDA, 'YYYY') AS "ANO"
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO
WHERE N.CPF = '50534475787' AND TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
GROUP BY N.CPF,TO_CHAR(N.DATA_VENDA, 'YYYY')

--*************OPINIAO DO INSTRUTOR*************************************
SELECT 'O cliente ' || TC.NOME || ' faturou ' || 
TO_CHAR(ROUND(SUM(INF.QUANTIDADE * INF.preco),2)) || ' no ano de ' || TO_CHAR(DATA_VENDA, 'YYYY') AS SENTENCA 
FROM notas_fiscais NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY')
ORDER BY TC.NOME;


------MEU ---PROCESSO----ATE----ENCONTRAR-----A------RESPOSTA---------
SELECT SUM(QUANTIDADE*PRECO) AS "SOMA", NUMERO FROM ITENS_NOTAS_FISCAIS
WHERE NUMERO = 100
GROUP BY NUMERO;


SELECT N.CPF, SUM(I.QUANTIDADE * I.PRECO), SUM(I.QUANTIDADE)
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO
GROUP BY N.CPF;

SELECT SUM(I.QUANTIDADE * I.PRECO) AS "FATURAMENTO",
SUM(I.QUANTIDADE) AS "TOTAL", N.CPF, TO_CHAR(N.DATA_VENDA, 'YYYY')
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON I.NUMERO = N.NUMERO
WHERE TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
GROUP BY N.CPF, TO_CHAR(N.DATA_VENDA, 'YYYY')
ORDER BY N.CPF;

SELECT CPF, COUNT(CPF) FROM NOTAS_FISCAIS GROUP BY CPF;
SELECT * FROM NOTAS_FISCAIS WHERE CPF = '95939180787';

