SELECT * FROM TABAELA_DE_PRODUTOS;

SELECT SABOR, 
       AVG(PRECO_DE_LISTA) AS "MEDIA"
FROM TABELA_DE_PRODUTOS
GROUP BY SABOR;

-----------------------------------------------

SELECT X.SABOR, 
       X.MEDIA 
FROM 
    (SELECT SABOR, 
            AVG(PRECO_DE_LISTA) AS "MEDIA"
    FROM TABELA_DE_PRODUTOS
    GROUP BY SABOR) X
WHERE X.MEDIA > 10;

----CREATE VIEW-------------
CREATE VIEW VW_MEDIA_POR_SABOR AS
    SELECT SABOR, 
       AVG(PRECO_DE_LISTA) AS "MEDIA"
    FROM TABELA_DE_PRODUTOS
    GROUP BY SABOR;
    
----CREATE VIEW-------------
CREATE OR REPLACE VIEW VW_MEDIA_POR_SABOR AS
    SELECT SABOR, 
       AVG(PRECO_DE_LISTA) AS "MEDIA"
    FROM TABELA_DE_PRODUTOS
    GROUP BY SABOR;    
    
---UTILIZANDO A VIEW
SELECT * 
FROM VW_MEDIA_POR_SABOR;

----UTILIZANDO A VIEW COM PARAMETRO
SELECT * 
FROM VW_MEDIA_POR_SABOR
WHERE MEDIA > 10;

---EXCLUINDO VIEW -----
DROP VIEW VW_MEDIA_POR_SABOR;