SELECT * FROM TAB_FUNCIONARIO;
SELECT * FROM TAB_DEPARTAMENTO;
DESCRIBE TAB_DEPARTAMENTO;
SELECT * FROM TAB_PROJETO;
DESCRIBE TAB_PROJETO;

--CRIACAO DA TABELA AUXILIAR
CREATE TABLE TAB_DEP_PROJ_FATURAMENTO
(NOME_DEPARTAMENTO VARCHAR2(50),
ORCAMENTO FLOAT
);

--ELEBARACAO DO SELECT PARA A TRIGGER
SELECT D.NOME_DEPARTAMENTO, COUNT(F.COD_FUNCIONARIO) AS QTD, SUB_SEL.SOMA, ROUND(SUB_SEL.SOMA / COUNT(F.COD_FUNCIONARIO),1) AS TOTAL
FROM TAB_FUNCIONARIO F
INNER JOIN
(SELECT P.COD_DEPARTAMENTO, SUM(P.ORCAMENTO) AS SOMA
FROM TAB_PROJETO P
GROUP BY P.COD_DEPARTAMENTO) SUB_SEL
ON F.COD_DEPARTAMENTO = SUB_SEL.COD_DEPARTAMENTO
INNER JOIN TAB_DEPARTAMENTO D
ON F.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO
GROUP BY D.NOME_DEPARTAMENTO,  SUB_SEL.SOMA;

--ELEBARACAO DO SELECT  COM INSERT PARA A TRIGGER
INSERT INTO TAB_DEP_PROJ_FATURAMENTO
SELECT D.NOME_DEPARTAMENTO, ROUND(SUB_SEL.SOMA / COUNT(F.COD_FUNCIONARIO),1) AS TOTAL
FROM TAB_FUNCIONARIO F
INNER JOIN
(SELECT P.COD_DEPARTAMENTO, SUM(P.ORCAMENTO) AS SOMA
FROM TAB_PROJETO P
GROUP BY P.COD_DEPARTAMENTO) SUB_SEL
ON F.COD_DEPARTAMENTO = SUB_SEL.COD_DEPARTAMENTO
INNER JOIN TAB_DEPARTAMENTO D
ON F.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO
GROUP BY D.NOME_DEPARTAMENTO,  SUB_SEL.SOMA;

--ELEBARACAO DO SELECT  COM INSERT E DELETE PARA A TRIGGER
--O DELETE SERVE APENAS PARA NAO FICAR INSERINDO VARIAS LINHAS COM O MESMO VALOR
DELETE FROM TAB_DEP_PROJ_FATURAMENTO;
INSERT INTO TAB_DEP_PROJ_FATURAMENTO
SELECT D.NOME_DEPARTAMENTO, ROUND(SUB_SEL.SOMA / COUNT(F.COD_FUNCIONARIO),1) AS TOTAL
FROM TAB_FUNCIONARIO F
INNER JOIN
(SELECT P.COD_DEPARTAMENTO, SUM(P.ORCAMENTO) AS SOMA
FROM TAB_PROJETO P
GROUP BY P.COD_DEPARTAMENTO) SUB_SEL
ON F.COD_DEPARTAMENTO = SUB_SEL.COD_DEPARTAMENTO
INNER JOIN TAB_DEPARTAMENTO D
ON F.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO
GROUP BY D.NOME_DEPARTAMENTO,  SUB_SEL.SOMA;

--DROP TRIGGER TG_TAB_DEP_PROJ_FATURAMENTO;
--ADICIONANDO A TRIGGER
CREATE OR REPLACE TRIGGER TG_TAB_DEP_PROJ_FATURAMENTO
AFTER INSERT OR UPDATE OR DELETE ON TAB_PROJETO
BEGIN
DELETE FROM TAB_DEP_PROJ_FATURAMENTO;
INSERT INTO TAB_DEP_PROJ_FATURAMENTO
SELECT D.NOME_DEPARTAMENTO, ROUND(SUB_SEL.SOMA / COUNT(F.COD_FUNCIONARIO),1) AS TOTAL
FROM TAB_FUNCIONARIO F
INNER JOIN
(SELECT P.COD_DEPARTAMENTO, SUM(P.ORCAMENTO) AS SOMA
FROM TAB_PROJETO P
GROUP BY P.COD_DEPARTAMENTO) SUB_SEL
ON F.COD_DEPARTAMENTO = SUB_SEL.COD_DEPARTAMENTO
INNER JOIN TAB_DEPARTAMENTO D
ON F.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO
GROUP BY D.NOME_DEPARTAMENTO,  SUB_SEL.SOMA;
END;

--INSERINDO PARA CONFIRMAR A TRIGGER
INSERT INTO TAB_DEPARTAMENTO
VALUES('D0006', 'DEPARTAMENTO D0006', 'EMBU DAS ARTES', 'E0002');
INSERT INTO TAB_FUNCIONARIO
VALUES('F0036', 'FUNCIONARIO F0036','01/02/22','D0006');
INSERT INTO TAB_PROJETO
VALUES('P0013', 'PROJETO P0013','50000','05/04/22','D0006');

INSERT INTO TAB_DEPARTAMENTO
VALUES('D0007', 'DEPARTAMENTO D0007', 'EMBU DAS ARTES', 'E0002');
INSERT INTO TAB_FUNCIONARIO
VALUES('F0037', 'FUNCIONARIO F0037','01/02/22','D0007');
INSERT INTO TAB_FUNCIONARIO
VALUES('F0038', 'FUNCIONARIO F0038','01/02/22','D0007');
INSERT INTO TAB_FUNCIONARIO
VALUES('F0039', 'FUNCIONARIO F0039','01/02/22','D0007');
INSERT INTO TAB_PROJETO
VALUES('P0014', 'PROJETO P0014','80000','05/04/22','D0007');

--DELETANDO PARA CONFERIR A TRIGGER -- FORMA INCORRETA DE DELETAR, MAS PRO EXERCICIO É A MAIS RAPIDA
--APAGANDO APENAS OS INSERTS RECENTES EFETUADOS ACIMA;
DELETE FROM TAB_PROJETO WHERE COD_DEPARTAMENTO = 'D0006';
DELETE FROM TAB_PROJETO WHERE COD_DEPARTAMENTO = 'D0007';
DELETE FROM TAB_FUNCIONARIO WHERE COD_DEPARTAMENTO = 'D0006';
DELETE FROM TAB_FUNCIONARIO WHERE COD_DEPARTAMENTO = 'D0007';
DELETE FROM TAB_DEPARTAMENTO WHERE COD_DEPARTAMENTO = 'D0006';
DELETE FROM TAB_DEPARTAMENTO WHERE COD_DEPARTAMENTO = 'D0007';

--VERIFICACAO APOS OS INSERTS E DELETES 
SELECT * FROM TAB_DEP_PROJ_FATURAMENTO;

COMMIT;