DELETE FROM ITENS_NOTAS;
DELETE FROM NOTAS;

SELECT * FROM CLIENTES;
--1471156710
SELECT * FROM VENDEDORES;
--235
SELECT * FROM PRODUTOS;
--1000889

SELECT * FROM NOTAS;
INSERT INTO NOTAS
(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('001', TO_DATE('2022-01-01', 'YYYY-MM-DD'), '1471156710','235', 0.1);
INSERT INTO NOTAS
(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('002', TO_DATE('2022-01-01', 'YYYY-MM-DD'), '1471156710','235', 0.1);
INSERT INTO NOTAS
(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('003', TO_DATE('2019-01-02', 'YYYY-MM-DD'), '1471156710','235', 0.1);
--COLOQUEI O ANO ERRADO, FIZ UPDATE DO ANO
UPDATE NOTAS
SET DATA_VENDA = TO_DATE('2019-01-01', 'YYYY-MM-DD')
WHERE NUMERO IN ('001','002');


SELECT * FROM ITENS_NOTAS;
INSERT INTO ITENS_NOTAS
(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('001', '1000889', 10,10);
INSERT INTO ITENS_NOTAS
(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('002', '1000889', 15,10);
INSERT INTO ITENS_NOTAS
(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('003', '1000889', 18,10);


--RELATORIO DE CONSULTA, DO TOTAL POR DIA
SELECT N.DATA_VENDA,
       SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

--CRIACAO DA TABELA FATURFAMENTO, DEVIDO AO CODIGO ACIMA SER MUITO CUSTOSO
CREATE TABLE TAB_FATURAMENTO (DATA_VENDA DATE NULL, FATURAMENTO FLOAT); 

--INSERINDO DADOS NA TABELA TAB_FATURAMENTO
INSERT INTO TAB_FATURAMENTO
SELECT N.DATA_VENDA,
       SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

--SE INSERIR NOVOS CAMPOS NA TABELA NOTAS E ITENS VAI APARECER EM TAB_FATURAMENTO, MAS NAO ATUALIZADO
INSERT INTO NOTAS
(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('004', TO_DATE('2019-01-02', 'YYYY-MM-DD'), '1471156710','235', 0.1);
INSERT INTO ITENS_NOTAS
(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('004', '1000889', 21,10);

--NECESSARIO DAR UM DELETE PARA VISUALIZA ATUALIZADO SEM RECOPIAR AMTERIORES
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT N.DATA_VENDA,
       SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
INNER JOIN ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;
SELECT * FROM TAB_FATURAMENTO;
--ESTE EXEMPLO É PARA CRIACAO DA TRIGGER

COMMIT;