--CONTANDO O NUMERO DE FUNCIONARIOS DE ACORDO COM O DEPARTAMENTO
SELECT TD.COD_DEPARTAMENTO, COUNT(*) AS NUM_FUNCIONARIOS FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
GROUP BY TD.COD_DEPARTAMENTO;

--VALOR TOTAL DO ORCAMENTO DE ACORDO COM O DEPARTAMENTO
SELECT TD.COD_DEPARTAMENTO, SUM(TP.ORCAMENTO) AS ORCAMENTO FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.COD_DEPARTAMENTO;

--JUNTANDO OS SCRIPTS ACIMA
SELECT TD.COD_DEPARTAMENTO, COUNT(*) AS NUM_FUNCIONARIOS, 
SUM(TP.ORCAMENTO) AS ORCAMENTO FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.COD_DEPARTAMENTO;

--DIVIDINDO O TOTAL PELO NUMERO DE FUNCIONARIOS
SELECT TD.NOME_DEPARTAMENTO AS DEPARTAMENTO, 
SUM(TP.ORCAMENTO)/COUNT(*) AS VALOR FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.NOME_DEPARTAMENTO;

--CRIANDO A TABELA AUXILIAR
CREATE TABLE TAB_FUNCIONARIO_ORCAMENTO
(DEPARTAMENTO VARCHAR(100), VALOR FLOAT);

-- É NECESSARIO UMA TRIGGER PARA CADA TABELA, POIS SE ALTERAR FUNCIONARIO A QUANTIDADE DO ORCAMENTO SERA MENOR CASO NAO TENHA ALTERACAO NA TABELAPROJETO ORCAMENTO
CREATE OR REPLACE TRIGGER TG_TAB_FUNCIONARIO
AFTER INSERT OR UPDATE OR DELETE ON TAB_FUNCIONARIO
BEGIN
DELETE FROM TAB_FUNCIONARIO_ORCAMENTO;
INSERT INTO TAB_FUNCIONARIO_ORCAMENTO
SELECT TD.NOME_DEPARTAMENTO AS DEPARTAMENTO, 
SUM(TP.ORCAMENTO)/COUNT(*) AS VALOR FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.NOME_DEPARTAMENTO;
END;

--SE O VALOR DO PROJETO AUMENTAR, O VALOR FINAL SRRA DIFERENTE
CREATE OR REPLACE TRIGGER TG_TAB_PROJETO
AFTER INSERT OR UPDATE OR DELETE ON TAB_PROJETO
BEGIN
DELETE FROM TAB_FUNCIONARIO_ORCAMENTO;
INSERT INTO TAB_FUNCIONARIO_ORCAMENTO
SELECT TD.NOME_DEPARTAMENTO AS DEPARTAMENTO, 
SUM(TP.ORCAMENTO)/COUNT(*) AS VALOR FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.NOME_DEPARTAMENTO;
END;

--AQUI SE SETORES FOREM EXCLUIDOS, ALTERADOS OU CRIADOS, MODIFICARAO A TABELA
CREATE OR REPLACE TRIGGER TG_TAB_DEPARTAMENTO
AFTER INSERT OR UPDATE OR DELETE ON TAB_DEPARTAMENTO
BEGIN
DELETE FROM TAB_FUNCIONARIO_ORCAMENTO;
INSERT INTO TAB_FUNCIONARIO_ORCAMENTO
SELECT TD.NOME_DEPARTAMENTO AS DEPARTAMENTO, 
SUM(TP.ORCAMENTO)/COUNT(*) AS VALOR FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.NOME_DEPARTAMENTO;
END;




------------------------------------------

SELECT TD.COD_DEPARTAMENTO, COUNT(TF.COD_FUNCIONARIO) AS NUM_FUNCIONARIOS, 
SUM(TP.ORCAMENTO) AS ORCAMENTO FROM
TAB_DEPARTAMENTO TD
INNER JOIN
TAB_FUNCIONARIO TF
ON TD.COD_DEPARTAMENTO = TF.COD_DEPARTAMENTO
INNER JOIN
TAB_PROJETO TP
ON TD.COD_DEPARTAMENTO = TP.COD_DEPARTAMENTO
GROUP BY TD.COD_DEPARTAMENTO;