SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES; -- 12 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; -- 4 BAIRROS

-- UNION SELECIONA OS BAIRROS SEM REPETIR TOTAL(13)
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- UNION ALL SE REPETEM (TOTAL DE 12 + 4)
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- UNION ALL SE REPETEM (TOTAL DE 12 + 4), CONSTANTE
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;


-- CONSTANTE no union fica igual o union all
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
