SELECT * FROM PRODUTOS 
WHERE CODIGO = '1040107';

UPDATE PRODUTOS
SET PRECO_LISTA = 5.2
WHERE CODIGO = '1040107';

UPDATE PRODUTOS
SET SABOR = 'Laranja', EMBALAGEM = 'PET'
WHERE CODIGO = '1040107';

--REPLACE ALTERA PARTE DE UM TEXTO
SELECT DESCRITOR, REPLACE(DESCRITOR, 'Melancia', 'Laranja')
FROM PRODUTOS
WHERE CODIGO = '1040107';

--UPDATE COM REPLACE
UPDATE PRODUTOS
SET DESCRITOR = REPLACE(DESCRITOR, 'Melancia', 'Laranja')
where codigo = '1040107';


SELECT * FROM PRODUTOS WHERE SABOR = 'Maracuja';

--ADICIONANDO 10% AO VALOR DO PRODUTO
UPDATE PRODUTOS
SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Maracuja';