/*
Vendas percentuais por tamanho
Modifique o relatório, 
mas agora para ver o ranking das vendas por tamanho.
*/

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

-- ESTE CASO EU PEGO A PORCENTAGEM DO ANO COMPARADO AO TOTAL DE VENDAS, INDEPENDENTE DO ANO
SELECT SUB_SEL.TAMANHO,SUB_SEL.EMBALAGEM, TO_CHAR(N.DATA_VENDA, 'YYYY') AS "ANO",
SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) AS "SOMA_TOTAL", 
ROUND((SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) / SUB_SEL.FATURAMENTO_TOTAL) * 100,2) || '% ' AS "PERCENTUAL"
FROM
(SELECT P.CODIGO_DO_PRODUTO, P.EMBALAGEM, P.TAMANHO, I.QUANTIDADE, I.PRECO, I.NUMERO,
(SELECT ROUND(SUM(QUANTIDADE * PRECO),2)
FROM ITENS_NOTAS_FISCAIS) FATURAMENTO_TOTAL
FROM TABELA_DE_PRODUTOS P, ITENS_NOTAS_FISCAIS I
WHERE P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
GROUP BY P.CODIGO_DO_PRODUTO, P.TAMANHO, P.EMBALAGEM , I.QUANTIDADE, I.PRECO, I.NUMERO
ORDER BY P.CODIGO_DO_PRODUTO) SUB_SEL, NOTAS_FISCAIS N
WHERE SUB_SEL.NUMERO = N.NUMERO AND TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
GROUP BY SUB_SEL.TAMANHO,SUB_SEL.EMBALAGEM, TO_CHAR(N.DATA_VENDA, 'YYYY'),SUB_SEL.FATURAMENTO_TOTAL
ORDER BY ROUND((SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) / SUB_SEL.FATURAMENTO_TOTAL) * 100,2) DESC;

--FATURAMENTO TOTAL GERAL
SELECT ROUND(SUM(QUANTIDADE * PRECO),2)
FROM ITENS_NOTAS_FISCAIS;

--FATURAMENTO TOTAL ANUAL
SELECT ROUND(SUM(I.QUANTIDADE * I.PRECO),2) AS "SOMA_TOTAL"
FROM ITENS_NOTAS_FISCAIS I, NOTAS_FISCAIS N
WHERE N.NUMERO = I.NUMERO AND TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016;



-- FATURAMENTO ANUAL 2016 = 42362118.19
SELECT SUB_SEL.TAMANHO,
       SUB_SEL.EMBALAGEM, 
       TO_CHAR(N.DATA_VENDA, 'YYYY') AS "ANO",
       SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) AS "SOMA_TOTAL", 
       ROUND((SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) / SUB_SEL.FATURAMENTO_TOTAL) * 100,2) || '% ' AS "PERCENTUAL"
FROM
      (SELECT P.CODIGO_DO_PRODUTO, 
              P.EMBALAGEM, P.TAMANHO, 
              I.QUANTIDADE, 
              I.PRECO, 
              I.NUMERO,
             (SELECT ROUND(SUM(I.QUANTIDADE * I.PRECO),2) AS "SOMA_TOTAL"
              FROM ITENS_NOTAS_FISCAIS I, NOTAS_FISCAIS N
              WHERE N.NUMERO = I.NUMERO 
                    AND TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
              GROUP BY TO_CHAR(N.DATA_VENDA, 'YYYY')) FATURAMENTO_TOTAL
        FROM TABELA_DE_PRODUTOS P, 
             ITENS_NOTAS_FISCAIS I
        WHERE P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
        GROUP BY P.CODIGO_DO_PRODUTO,
                 P.TAMANHO, 
                 P.EMBALAGEM , 
                 I.QUANTIDADE, 
                 I.PRECO, 
                 I.NUMERO
        ORDER BY P.CODIGO_DO_PRODUTO) SUB_SEL, 
NOTAS_FISCAIS N
WHERE SUB_SEL.NUMERO = N.NUMERO 
AND TO_CHAR(N.DATA_VENDA, 'YYYY') = 2016
GROUP BY SUB_SEL.TAMANHO,
         SUB_SEL.EMBALAGEM, TO_CHAR(N.DATA_VENDA, 'YYYY'),
         SUB_SEL.FATURAMENTO_TOTAL
ORDER BY ROUND((SUM(SUB_SEL.QUANTIDADE * SUB_SEL.PRECO) / SUB_SEL.FATURAMENTO_TOTAL) * 100,2) DESC;


---- TENTAR PRIMEIRO COM NOTAS_FISCAIS E ITENS_NOTASFISCAIS

