/*
Vamos para mais um desafio. Nosso usuário pediu para fazermos o seguinte relatório: 
ele quer ver um ranking das vendas de produtos por sabor, do sabor que mais vendeu 
para o que menos vendeu dentro de um ano específico (o ano será um parâmetro de filtro). 
Além de montar esse ranking por sabor, ele quer criar uma coluna de percentual de 
distribuição daquele sabor em relação às vendas totais.
*/

--PRIMEIRA ETAPA ENCONTRAR OS COMPOS PRINCIPAIS
SELECT TP.SABOR, SUM(INF.QUANTIDADE) AS "TOTAL_QUANTIDADE_LITROS", EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO" 
FROM TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF 
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO 
INNER JOIN NOTAS_FISCAIS NF 
ON INF.NUMERO = NF.NUMERO
WHERE  EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

----TOTAL DE VENDA TOTAL DEIXANDO EM UM UNICO CAMPO---
SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", SUM(INF.QUANTIDADE) AS "QUANTIDADE_GERAL"
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO;

--- ADICIONANDO A QUANTIDADE GERAL EM TODAS AS LINHAS USANDO O SCRIPT ANTRIOR
SELECT TP.SABOR, SUM(INF.QUANTIDADE) AS "TOTAL_QUANTIDADE_LITROS", EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", 
(SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", SUM(INF.QUANTIDADE) AS "QUANTIDADE_GERAL"
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO) QUANTIDADE_GERAL
FROM TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF 
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO 
INNER JOIN NOTAS_FISCAIS NF 
ON INF.NUMERO = NF.NUMERO
WHERE  EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT RELATORIO_GERAL.SABOR, RELATORIO_GERAL.TOTAL_QUANTIDADE_LITROS,RELATORIO_GERAL.ANO,
--RELATORIO_GERAL.QUANTIDADE_GERAL, 
ROUND(RELATORIO_GERAL.TOTAL_QUANTIDADE_LITROS/ RELATORIO_GERAL.QUANTIDADE_GERAL * 100, 2) || ' % ' AS "PARTICIPACAO_%" 
FROM
(SELECT TP.SABOR, SUM(INF.QUANTIDADE) AS "TOTAL_QUANTIDADE_LITROS", EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", 
(SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", SUM(INF.QUANTIDADE) AS "QUANTIDADE_GERAL"
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO) QUANTIDADE_GERAL
FROM TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF 
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO 
INNER JOIN NOTAS_FISCAIS NF 
ON INF.NUMERO = NF.NUMERO
WHERE  EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) RELATORIO_GERAL;


---MINHA TENTATIVA DE RESUMIR O CODIGO
SELECT TP.SABOR, SUM(INF.QUANTIDADE) as "QUANTIDADE", RELATORIO_GERAL.ANO,
ROUND(SUM(INF.QUANTIDADE)/ RELATORIO_GERAL.QUANTIDADE_GERAL * 100, 2) || ' % ' AS "PARTICIPACAO_%"
FROM
(SELECT EXTRACT(YEAR FROM NF.DATA_VENDA) AS "ANO", SUM(INF.QUANTIDADE) AS "QUANTIDADE_GERAL"
FROM NOTAS_FISCAIS NF, ITENS_NOTAS_FISCAIS INF
WHERE NF.NUMERO = INF.NUMERO AND EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) RELATORIO_GERAL, TABELA_DE_PRODUTOS TP, ITENS_NOTAS_FISCAIS INF, NOTAS_FISCAIS NF 
WHERE (TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO AND INF.NUMERO = NF.NUMERO) AND EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, RELATORIO_GERAL.QUANTIDADE_GERAL, RELATORIO_GERAL.ANO
ORDER BY SUM(INF.QUANTIDADE) DESC;
