INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00233', 'Joao Geraldo da Fonseca', '01/12/2015', 10.00);


INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00400', 'Maria do Rosario', '23/07/2012', 0.15);

INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00810', 'Marcia Almeida', '14/12/2016', 0.18);


INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00414', 'Carlos Moreira', '13/11/2015', 0.14);

INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00934', 'Juvenildo Martin', '09/03/2010', 0.20);

INSERT ALL 
INTO TB_VENDEDORES(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00933', 'Juvenildo Martin', '09/03/2010', 0.20)
INTO TB_VENDEDORES(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES('00939', 'Juvenildo Martinerri', '06/05/2010', 0.20)
SELECT * FROM dual;

describe TB_VENDEDORES;


select * from TB_VENDEDORES;

alter table TB_VENDEDORES
modify  PERC_COMISSAO_VENDEDOR number(5,2);

DELETE FROM TB_VENDEDORES WHERE MATRI_VENDEDOR = '00233';

select * from TB_VENDEDORES
where DATA_ADMISSAO_VENDEDOR = '01/12/2015';

update TB_VENDEDORES
set PERC_COMISSAO_VENDEDOR = 0.10
where MATRI_VENDEDOR = '00233';