SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, 
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MÉDIO'
      ELSE 'CLIENTE PEQUENO'
      END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;