SELECT * FROM TB_VENDEDORES;

ALTER TABLE TB_VENDEDORES
ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY(MATRI_VENDEDOR);

INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('00352', 'Super Menos', '31/05/2020', 0.10);
INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('01000', 'Salarios Baixus', '31/05/2021', 0.05);
INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('01020', 'Jonh Wayne', '31/10/2018', 0.08);
INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('01030', 'Katy Peterson', '30/09/2018', 0.08);
INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('01050', 'Rodrigo Almeida', '31/10/2020', 0.01);
INSERT INTO TB_VENDEDORES
(MATRI_VENDEDOR, NOME_VENDEDOR, DATA_ADMISSAO_VENDEDOR, PERC_COMISSAO_VENDEDOR)
VALUES
('01010', 'Patricia Martins', '31/05/2021', 0.05);


SELECT * FROM TB_VENDEDORES WHERE PERC_COMISSAO_VENDEDOR < 0.17;