SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME,BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, CIDADE, BAIRRO  FROM TABELA_DE_CLIENTES;

SELECT CPF  IDENTIFICADOR, NOME AS "NOME DO CLIENTE",BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF IDENTIFICADOR, NOME AS "NOME DO CLIENTE", TDC.BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;