SELECT CODIGO_DO_PRODUTO, COUNT(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035'
GROUP BY CODIGO_DO_PRODUTO;


SELECT COUNT(CODIGO_DO_PRODUTO), SUM(QUANTIDADE) 
FROM ITENS_NOTAS_FISCAIS
HAVING SUM(QUANTIDADE) > 394000
HAVING COUNT(CODIGO_DO_PRODUTO);
