SELECT * FROM TABELA_DE_PRODUTOS;

SELECT SABOR FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT BAIRRO FROM TABELA_DE_CLIENTES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
