SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';

-- NAO E IGUAL A MANGA E NAO E IGUAL 470ML (DIFERENTE DE MANGA E DIFERENTE DE 470 ML)
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT(SABOR = 'Manga' OR TAMANHO = '470 ml');

-- NAO E IGUAL A MANGA OU NAO E IGUAL 470ML (DIFERENTE DE MANGA OU DIFERENTE DE 470 ML)
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT(SABOR = 'Manga' AND TAMANHO = '470 ml');


SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Melancia' OR SABOR = 'Laranja';
-- RESUMINDO A QUERY ACIMA
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Manga', 'Melancia', 'Laranja');


SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Manga', 'Melancia', 'Laranja') AND TAMANHO = '1 Litro';


SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('Sao Paulo', 'Rio de Janeiro') AND IDADE >= 20;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('Sao Paulo', 'Rio de Janeiro') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('Sao Paulo', 'Rio de Janeiro') AND (IDADE BETWEEN 20 AND 25);
