SELECT P.NOME_DO_PRODUTO, I.CODIGO_DO_PRODUTO, SUM(I.QUANTIDADE) 
FROM TABELA_DE_PRODUTOS P
INNER JOIN ITENS_NOTAS_FISCAIS I
ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
GROUP BY I.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO 
HAVING SUM(I.QUANTIDADE) > 394000 
ORDER BY SUM(I.QUANTIDADE) DESC;

SELECT COUNT(*) AS "MAIORES QUE 394000" FROM(SELECT P.NOME_DO_PRODUTO, I.CODIGO_DO_PRODUTO, SUM(I.QUANTIDADE) 
FROM TABELA_DE_PRODUTOS P
INNER JOIN ITENS_NOTAS_FISCAIS I
ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
GROUP BY I.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO 
HAVING SUM(I.QUANTIDADE) > 394000 
ORDER BY SUM(I.QUANTIDADE) DESC);

-- REDUCAO DO CODIGO ACIMA
SELECT COUNT(*) AS "MAIORES QUE 394000" FROM(SELECT SUM(QUANTIDADE) 
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO 
HAVING SUM(QUANTIDADE) > 394000 );

SELECT  SABOR, COUNT(*) 
FROM TABELA_DE_PRODUTOS
GROUP BY SABOR
ORDER BY SABOR;

SELECT COUNT (*) from (SELECT COUNT(*) 
FROM TABELA_DE_PRODUTOS
GROUP BY SABOR);

SELECT COUNT (*) from (SELECT DISTINCT SABOR 
FROM TABELA_DE_PRODUTOS);