-- INNER JOIN
SELECT 
C.CPF AS "CPF_DO_CADASTRO", C.NOME AS "NOME_DO_CLIENTE",
N.CPF AS "CPF_NOTAS_FISCAIS"
FROM
TABELA_DE_CLIENTES C
INNER JOIN
NOTAS_FISCAIS N
ON C.CPF = N.CPF;

SELECT DISTINCT
C.CPF AS "CPF_DO_CADASTRO", C.NOME AS "NOME_DO_CLIENTE",
N.CPF AS "CPF_NOTAS_FISCAIS"
FROM
TABELA_DE_CLIENTES C
INNER JOIN
NOTAS_FISCAIS N
ON C.CPF = N.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);

-- LEFT JOIN
SELECT DISTINCT
C.CPF AS "CPF_DO_CADASTRO", C.NOME AS "NOME_DO_CLIENTE",
N.CPF AS "CPF_NOTAS_FISCAIS"
FROM
TABELA_DE_CLIENTES C
LEFT JOIN
NOTAS_FISCAIS N
ON C.CPF = N.CPF;

-- LEFT JOIN + IS NULL
SELECT DISTINCT
C.CPF AS "CPF_DO_CADASTRO", C.NOME AS "NOME_DO_CLIENTE",
N.CPF AS "CPF_NOTAS_FISCAIS"
FROM
TABELA_DE_CLIENTES C
LEFT JOIN
NOTAS_FISCAIS N
ON C.CPF = N.CPF
WHERE N.CPF IS NULL;

SELECT DISTINCT
C.CPF AS "CPF_DO_CADASTRO", C.NOME AS "NOME_DO_CLIENTE"
FROM
TABELA_DE_CLIENTES C
LEFT JOIN
NOTAS_FISCAIS N
ON C.CPF = N.CPF
WHERE N.CPF IS NULL;