SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS "NUMERO DE NOTAS"
FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT N.MATRICULA, V.NOME, COUNT(*) AS "NUMERO DE NOTAS"
FROM TABELA_DE_VENDEDORES V 
INNER JOIN
NOTAS_FISCAIS N
ON N.MATRICULA = V.MATRICULA
GROUP BY N.MATRICULA, V.NOME;