SELECT DISTINCT
V.NOME AS "NOME_D0_VENDEDOR", V.BAIRRO AS "BAIRRO_DO_VENDEDOR",
C.NOME AS "NOME_DO_CLIENTE", C.BAIRRO AS "BAIRRO_DO_CLIENTE"
FROM
TABELA_DE_CLIENTES C
INNER JOIN
TABELA_DE_VENDEDORES V
ON V.BAIRRO = C.BAIRRO;

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT
V.NOME AS "NOME_D0_VENDEDOR", V.BAIRRO AS "BAIRRO_DO_VENDEDOR",
C.NOME AS "NOME_DO_CLIENTE", C.BAIRRO AS "BAIRRO_DO_CLIENTE"
FROM
TABELA_DE_CLIENTES C
LEFT JOIN
TABELA_DE_VENDEDORES V
ON V.BAIRRO = C.BAIRRO;

SELECT DISTINCT
V.NOME AS "NOME_D0_VENDEDOR", V.BAIRRO AS "BAIRRO_DO_VENDEDOR",
C.NOME AS "NOME_DO_CLIENTE", C.BAIRRO AS "BAIRRO_DO_CLIENTE"
FROM
TABELA_DE_CLIENTES C
RIGHT JOIN
TABELA_DE_VENDEDORES V
ON V.BAIRRO = C.BAIRRO;

SELECT DISTINCT
V.NOME AS "NOME_D0_VENDEDOR", V.BAIRRO AS "BAIRRO_DO_VENDEDOR",
C.NOME AS "NOME_DO_CLIENTE", C.BAIRRO AS "BAIRRO_DO_CLIENTE"
FROM
TABELA_DE_CLIENTES C
FULL JOIN
TABELA_DE_VENDEDORES V
ON V.BAIRRO = C.BAIRRO;