alter table TB_CLIENTES2
add (CIDADE_CLIENTE varchar2(50));

INSERT INTO TB_CLIENTES2 (CPF_CLIENTE, NOME_CLIENTE, ENDERECO_CLIENTE, ENDERECO2_CLIENTE, BAIRRO_CLIENTE, ESTADO_CLIENTE, 
CEP_CLIENTE, DATA_NASC_CLIENTE, IDADE_CLIENTE, SEXO_CLIENTE, LIMITE_CREDITO, VOLUME_COMPRA_CLIENTE, PRIMEIRA_COMPRA_CLIENTE, CIDADE_CLIENTE)
VALUES
('00333434579', 'João da Pereira', 'Rua Projetada numero 12', NULL, 'BARRA DA TIJUCA', 'RJ', 
'22222222', TO_DATE('12/10/1965', 'MM/DD/YYYY'), 56, 'M', 100000, 2000, 0, 'RIO DE JANEIRO');

INSERT INTO TB_CLIENTES2 (CPF_CLIENTE, NOME_CLIENTE, ENDERECO_CLIENTE, ENDERECO2_CLIENTE, BAIRRO_CLIENTE, ESTADO_CLIENTE, 
CEP_CLIENTE, DATA_NASC_CLIENTE, IDADE_CLIENTE, SEXO_CLIENTE, LIMITE_CREDITO, VOLUME_COMPRA_CLIENTE, PRIMEIRA_COMPRA_CLIENTE, CIDADE_CLIENTE)
VALUES
('00333434579', 'João da Pereira', 'Rua Projetada numero 12', NULL, 'BARRA DA TIJUCA', 'RJ', 
'22222222', TO_DATE('01/30/1965', 'MM/DD/YYYY'), 56, 'M', 100000, 2000, 0, 'RIO DE JANEIRO');

INSERT INTO TB_CLIENTES2 (CPF_CLIENTE, NOME_CLIENTE, ENDERECO_CLIENTE, ENDERECO2_CLIENTE, BAIRRO_CLIENTE, ESTADO_CLIENTE, 
CEP_CLIENTE, DATA_NASC_CLIENTE, IDADE_CLIENTE, SEXO_CLIENTE, LIMITE_CREDITO, VOLUME_COMPRA_CLIENTE, PRIMEIRA_COMPRA_CLIENTE, CIDADE_CLIENTE)
VALUES
('00333434579', 'João da Pereira', 'Rua Projetada numero 12', NULL, 'BARRA DA TIJUCA', 'RJ', 
'22222222', '12/10/1965', 56, 'M', 100000, 2000, 0, 'RIO DE JANEIRO');


SELECT TO_CHAR(DATA_NASC_CLIENTE,'MM') FROM TB_CLIENTES2;

delete from TB_CLIENTES where CPF_CLIENTE = 1
select * from TB_CLIENTES2;
