SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

SELECT CODIGO_DO_PRODUTO, COUNT(QUANTIDADE) AS "QTD. VENDAS COM 99 LITROS" FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO;

SELECT COUNT(*) AS "QTD. VENDAS COM 99 LITROS" FROM ITENS_NOTAS_FISCAIS WHERE codigo_do_produto = '1101035' AND quantidade = 99;

SELECT COUNT(QUANTIDADE) AS "QTD. VENDAS COM 99 LITROS" FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO;
