UPDATE TB_VENDEDORES SET PERC_COMISSAO_VENDEDOR = 0.18 WHERE MATRI_VENDEDOR = '00233';

UPDATE TB_VENDEDORES SET PERC_COMISSAO_VENDEDOR = 0.18 WHERE MATRI_VENDEDOR = '00400';

UPDATE TB_VENDEDORES SET PERC_COMISSAO_VENDEDOR = 0.18 WHERE MATRI_VENDEDOR = '00414';

SELECT * FROM TB_VENDEDORES;