SELECT * FROM  TABELA_DE_PRODUTOS;

SELECT ROWNUM, TABELA_DE_PRODUTOS.* FROM TABELA_DE_PRODUTOS;

SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP;

SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <=5;

SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <=5;

SELECT ROWNUM, I.* FROM ITENS_NOTAS_FISCAIS I
WHERE ROWNUM <= 5 AND CODIGO_DO_PRODUTO = '1101035';

SELECT ROWNUM, I.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS I
WHERE ROWNUM <= 5 AND CODIGO_DO_PRODUTO = '1101035';
