SELECT * FROM TB_VENDEDORES, TB_CLIENTES;

SELECT NOME_VENDEDOR, NOME
FROM TB_VENDEDORES, TB_CLIENTES;

SELECT TB_VENDEDORES.NOME_VENDEDOR, TB_CLIENTES.NOME AS "NOME_CLIENTES"
FROM TB_VENDEDORES, TB_CLIENTES;

SELECT C.NOME, 
V.NOME_VENDEDOR AS "NOME_CLIENTES"
FROM TB_VENDEDORES V, TB_CLIENTES C;

SELECT NOME FROM TB_CLIENTES;

SELECT V.NOME_VENDEDOR
FROM TB_VENDEDORES V;

SELECT
    X.NOME CLIENTE,
    V.NOME_VENDEDOR VENDEDOR
FROM
    (SELECT NOME FROM TB_CLIENTES) X,
    TB_VENDEDORES V;