select * from TB_CLIENTES;

select * from TB_PRODUTOS;

SELECT PRODUTO,NOME,EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA FROM TB_PRODUTOS;

SELECT PRECO_LISTA,NOME,EMBALAGEM, TAMANHO, SABOR  FROM TB_PRODUTOS;

SELECT PRODUTO, NOME FROM TB_PRODUTOS;

--SELECT COM ALIAS
SELECT PRODUTO AS "CODIGO DO PRODUTO",NOME AS "NOME DO PRODUTO",EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA FROM TB_PRODUTOS;