INSERT INTO TB_PRODUTOS
(PRODUTO, NOME_PRODUTO, EMBALAGEM_PRODUTO, TAMANHO_PRODUTO, SABOR_PRODUTO, PRECO_LISTA_PRODUTO)
VALUES
('1037797', 'Clean - 2 Litros - Laranja', 
'PET', '2 Litros', 'Laranja', 16.01);


INSERT INTO TB_PRODUTOS
(PRODUTO, NOME_PRODUTO, EMBALAGEM_PRODUTO, TAMANHO_PRODUTO, SABOR_PRODUTO, PRECO_LISTA_PRODUTO)
VALUES
('1000889', 'Sabor da Montanha - 700 ml - Uva', 
'Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME_PRODUTO, EMBALAGEM_PRODUTO, TAMANHO_PRODUTO, SABOR_PRODUTO, PRECO_LISTA_PRODUTO)
VALUES
('1004327', 'Videira do Campo - 1,5 Litros - Melância', 
'PET', '1,5 Litros', 'Melância', 19.51);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME_PRODUTO,EMBALAGEM_PRODUTO, TAMANHO_PRODUTO, SABOR_PRODUTO, PRECO_LISTA_PRODUTO)
VALUES
('1037797B', 'Clean - 2 Litros - Laranja', 'PET','2 Litros','Laranja',16.01);


SELECT * FROM TB_PRODUTOS;

DESCRIBE TB_PRODUTOS;